//============================================================================
//  v60_op_pkg -- which instruction format an opcode is.
//
//  GENERATED by tools/v60x/gen_op_pkg.py from tools/v60x/insn_table.py.
//  Do not edit: edit the table and regenerate.  verif/v60x/run_v60x.sh checks
//  that this file matches its source.
//
//  Source: NEC_uPD70616_V60_DataBook_1986.pdf pp.3.296-3.299, the instruction
//  set summary's "Instruction Format" column, cross-checked where it can be
//  against the Programmer's Reference.  docs/v60/INSTRUCTION-FORMATS.md
//  carries the traps; tools/v60x/insn_table.py carries the table, the
//  placeholder-field expansion, the collision check and the two places the two
//  NEC documents disagree.
//
//  Three answers are possible for one opcode byte:
//
//    a format          the opcode says, on its own
//    FMT_I_OR_II       the table says "I, II" and the INSTRUCTION says which:
//                      Format I is `0 m d reg` and Format II is
//                      `1 m m' subop` in the same position, so bit 15 of the
//                      base word decides (p.3.293)
//    FMT_ESCAPE        the opcode is one of 0x58-0x5F, which carry a subop,
//                      and the format depends on it -- 0x5D is VIIb for EXTBF
//                      and CMPBF but VIIc for INSBF
//
//  op_format_first() gives the first two; op_format_escape() resolves the
//  third, from the same base-word byte that carries bit 15.
//============================================================================
`ifndef V60_OP_PKG_SV
`define V60_OP_PKG_SV

package v60_op_pkg;

import v60_fmt_pkg::*;
import v60_alu_pkg::*;

// The control transfers, which do not go through the ALU.  Their operations
// are quoted in tools/v60x/insn_table.py beside the table that names them.
typedef enum logic [3:0] {
    CTRL_NONE = 4'd0,
    CTRL_BCC  = 4'd1,   // conditional, PC relative
    CTRL_BSR  = 4'd2,   // PC relative, pushes the return address
    CTRL_JMP  = 4'd3,   // to an effective address
    CTRL_JSR  = 4'd4,   // to an effective address, pushes the return address
    CTRL_RSR  = 4'd5,   // pops it
    CTRL_DBCC = 4'd6,   // decrement, and branch while not zero
    CTRL_TB   = 4'd7,   // branch when the register is zero
    CTRL_CALL = 4'd8,   // to an effective address, passing the argument pointer
    CTRL_RET  = 4'd9,   // pops the PC and the argument pointer, then discards
    CTRL_RETIU= 4'd10,  // pops the PC and the PSW
    CTRL_RETIS= 4'd11   // the same, and privileged
} ctrl_op_e;

// The opcode byte alone.  Anything the table does not list is a reserved
// opcode -- "Reserved opcode exceptions occur when an attempt is made to
// execute an opcode which is not assigned a valid instruction"
// (Programmer's Reference S8).
function automatic insn_fmt_e op_format_first(input logic [7:0] op);
    insn_fmt_e r;
    begin
        case (op)
            8'h00: r = FMT_V;       // HALT
            8'h01: r = FMT_I_OR_II; // LDTASK
            8'h02: r = FMT_I_OR_II; // STPR
            8'h03: r = FMT_I_OR_II; // GETRA
            8'h04: r = FMT_I_OR_II; // GETPTE
            8'h05: r = FMT_I_OR_II; // GETATE
            8'h08: r = FMT_I_OR_II; // RVBIT
            8'h09: r = FMT_I_OR_II; // MOV.B
            8'h0A: r = FMT_I_OR_II; // MOVS.BH
            8'h0B: r = FMT_I_OR_II; // MOVZ.BH
            8'h0C: r = FMT_I_OR_II; // MOVS.BW
            8'h0D: r = FMT_I_OR_II; // MOVZ.BW
            8'h10: r = FMT_V;       // CLRTLBA
            8'h12: r = FMT_I_OR_II; // LDPR
            8'h13: r = FMT_I_OR_II; // UPDPSW.W
            8'h14: r = FMT_I_OR_II; // UPDPTE
            8'h15: r = FMT_I_OR_II; // UPDATE
            8'h19: r = FMT_I_OR_II; // MOVT.HB
            8'h1B: r = FMT_I_OR_II; // MOV.H
            8'h1C: r = FMT_I_OR_II; // MOVS.HW
            8'h1D: r = FMT_I_OR_II; // MOVZ.HW
            8'h20: r = FMT_I_OR_II; // IN
            8'h21: r = FMT_I_OR_II; // OUT
            8'h22: r = FMT_I_OR_II; // IN
            8'h23: r = FMT_I_OR_II; // OUT
            8'h24: r = FMT_I_OR_II; // IN
            8'h25: r = FMT_I_OR_II; // OUT
            8'h29: r = FMT_I_OR_II; // MOVT.WB
            8'h2B: r = FMT_I_OR_II; // MOVT.WH
            8'h2C: r = FMT_I_OR_II; // RVBYT
            8'h2D: r = FMT_I_OR_II; // MOV.W
            8'h38: r = FMT_I_OR_II; // NOT
            8'h39: r = FMT_I_OR_II; // NEG
            8'h3A: r = FMT_I_OR_II; // NOT
            8'h3B: r = FMT_I_OR_II; // NEG
            8'h3C: r = FMT_I_OR_II; // NOT
            8'h3D: r = FMT_I_OR_II; // NEG
            8'h3F: r = FMT_I_OR_II; // MOV.D
            8'h40: r = FMT_I_OR_II; // MOVEA
            8'h41: r = FMT_I_OR_II; // XCH
            8'h42: r = FMT_I_OR_II; // MOVEA
            8'h43: r = FMT_I_OR_II; // XCH
            8'h44: r = FMT_I_OR_II; // MOVEA
            8'h45: r = FMT_I_OR_II; // XCH
            8'h47: r = FMT_I_OR_II; // SETF
            8'h48: r = FMT_IV;      // BSR
            8'h49: r = FMT_II;      // CALL
            8'h4A: r = FMT_I_OR_II; // UPDPSW.H
            8'h4B: r = FMT_I_OR_II; // CHLVL
            8'h4C: r = FMT_I;       // CAXI
            8'h4D: r = FMT_I_OR_II; // CHKAR
            8'h4E: r = FMT_I_OR_II; // CHKAW
            8'h4F: r = FMT_I_OR_II; // CHKAE
            8'h50: r = FMT_I_OR_II; // REM
            8'h51: r = FMT_I_OR_II; // REMU
            8'h52: r = FMT_I_OR_II; // REM
            8'h53: r = FMT_I_OR_II; // REMU
            8'h54: r = FMT_I_OR_II; // REM
            8'h55: r = FMT_I_OR_II; // REMU
            8'h58: r = FMT_ESCAPE;  // escape
            8'h59: r = FMT_ESCAPE;  // escape
            8'h5A: r = FMT_ESCAPE;  // escape
            8'h5B: r = FMT_ESCAPE;  // escape
            8'h5C: r = FMT_ESCAPE;  // escape
            8'h5D: r = FMT_ESCAPE;  // escape
            8'h5E: r = FMT_ESCAPE;  // escape
            8'h5F: r = FMT_ESCAPE;  // escape
            8'h60: r = FMT_IV;      // Bcc
            8'h61: r = FMT_IV;      // Bcc
            8'h62: r = FMT_IV;      // Bcc
            8'h63: r = FMT_IV;      // Bcc
            8'h64: r = FMT_IV;      // Bcc
            8'h65: r = FMT_IV;      // Bcc
            8'h66: r = FMT_IV;      // Bcc
            8'h67: r = FMT_IV;      // Bcc
            8'h68: r = FMT_IV;      // Bcc
            8'h69: r = FMT_IV;      // Bcc
            8'h6A: r = FMT_IV;      // Bcc
            8'h6B: r = FMT_IV;      // Bcc
            8'h6C: r = FMT_IV;      // Bcc
            8'h6D: r = FMT_IV;      // Bcc
            8'h6E: r = FMT_IV;      // Bcc
            8'h6F: r = FMT_IV;      // Bcc
            8'h70: r = FMT_IV;      // Bcc
            8'h71: r = FMT_IV;      // Bcc
            8'h72: r = FMT_IV;      // Bcc
            8'h73: r = FMT_IV;      // Bcc
            8'h74: r = FMT_IV;      // Bcc
            8'h75: r = FMT_IV;      // Bcc
            8'h76: r = FMT_IV;      // Bcc
            8'h77: r = FMT_IV;      // Bcc
            8'h78: r = FMT_IV;      // Bcc
            8'h79: r = FMT_IV;      // Bcc
            8'h7A: r = FMT_IV;      // Bcc
            8'h7B: r = FMT_IV;      // Bcc
            8'h7C: r = FMT_IV;      // Bcc
            8'h7D: r = FMT_IV;      // Bcc
            8'h7E: r = FMT_IV;      // Bcc
            8'h7F: r = FMT_IV;      // Bcc
            8'h80: r = FMT_I_OR_II; // ADD
            8'h81: r = FMT_I_OR_II; // MUL
            8'h82: r = FMT_I_OR_II; // ADD
            8'h83: r = FMT_I_OR_II; // MUL
            8'h84: r = FMT_I_OR_II; // ADD
            8'h85: r = FMT_I_OR_II; // MUL
            8'h86: r = FMT_I_OR_II; // MULX
            8'h87: r = FMT_I_OR_II; // TEST1
            8'h88: r = FMT_I_OR_II; // OR
            8'h89: r = FMT_I_OR_II; // ROT
            8'h8A: r = FMT_I_OR_II; // OR
            8'h8B: r = FMT_I_OR_II; // ROT
            8'h8C: r = FMT_I_OR_II; // OR
            8'h8D: r = FMT_I_OR_II; // ROT
            8'h90: r = FMT_I_OR_II; // ADDC
            8'h91: r = FMT_I_OR_II; // MULU
            8'h92: r = FMT_I_OR_II; // ADDC
            8'h93: r = FMT_I_OR_II; // MULU
            8'h94: r = FMT_I_OR_II; // ADDC
            8'h95: r = FMT_I_OR_II; // MULU
            8'h96: r = FMT_I_OR_II; // MULUX
            8'h97: r = FMT_I_OR_II; // SET1
            8'h98: r = FMT_I_OR_II; // SUBC
            8'h99: r = FMT_I_OR_II; // ROTC
            8'h9A: r = FMT_I_OR_II; // SUBC
            8'h9B: r = FMT_I_OR_II; // ROTC
            8'h9C: r = FMT_I_OR_II; // SUBC
            8'h9D: r = FMT_I_OR_II; // ROTC
            8'hA0: r = FMT_I_OR_II; // AND
            8'hA1: r = FMT_I_OR_II; // DIV
            8'hA2: r = FMT_I_OR_II; // AND
            8'hA3: r = FMT_I_OR_II; // DIV
            8'hA4: r = FMT_I_OR_II; // AND
            8'hA5: r = FMT_I_OR_II; // DIV
            8'hA6: r = FMT_I_OR_II; // DIVX
            8'hA7: r = FMT_I_OR_II; // CLR1
            8'hA8: r = FMT_I_OR_II; // SUB
            8'hA9: r = FMT_I_OR_II; // SHL
            8'hAA: r = FMT_I_OR_II; // SUB
            8'hAB: r = FMT_I_OR_II; // SHL
            8'hAC: r = FMT_I_OR_II; // SUB
            8'hAD: r = FMT_I_OR_II; // SHL
            8'hB0: r = FMT_I_OR_II; // XOR
            8'hB1: r = FMT_I_OR_II; // DIVU
            8'hB2: r = FMT_I_OR_II; // XOR
            8'hB3: r = FMT_I_OR_II; // DIVU
            8'hB4: r = FMT_I_OR_II; // XOR
            8'hB5: r = FMT_I_OR_II; // DIVU
            8'hB6: r = FMT_I_OR_II; // DIVUX
            8'hB7: r = FMT_I_OR_II; // NOT1
            8'hB8: r = FMT_I_OR_II; // CMP
            8'hB9: r = FMT_I_OR_II; // SHA
            8'hBA: r = FMT_I_OR_II; // CMP
            8'hBB: r = FMT_I_OR_II; // SHA
            8'hBC: r = FMT_I_OR_II; // CMP
            8'hBD: r = FMT_I_OR_II; // SHA
            8'hC6: r = FMT_VI;      // DBcc
            8'hC7: r = FMT_VI;      // TB
            8'hC8: r = FMT_V;       // BRK
            8'hC9: r = FMT_V;       // BRKV
            8'hCA: r = FMT_V;       // RSR
            8'hCB: r = FMT_V;       // TRAPFL
            8'hCC: r = FMT_V;       // DISPOSE
            8'hCD: r = FMT_V;       // NOP
            8'hD0: r = FMT_III;     // DEC
            8'hD1: r = FMT_III;     // DEC
            8'hD2: r = FMT_III;     // DEC
            8'hD3: r = FMT_III;     // DEC
            8'hD4: r = FMT_III;     // DEC
            8'hD5: r = FMT_III;     // DEC
            8'hD6: r = FMT_III;     // JMP
            8'hD7: r = FMT_III;     // JMP
            8'hD8: r = FMT_III;     // INC
            8'hD9: r = FMT_III;     // INC
            8'hDA: r = FMT_III;     // INC
            8'hDB: r = FMT_III;     // INC
            8'hDC: r = FMT_III;     // INC
            8'hDD: r = FMT_III;     // INC
            8'hDE: r = FMT_III;     // PREPARE
            8'hDF: r = FMT_III;     // PREPARE
            8'hE0: r = FMT_III;     // TASI
            8'hE1: r = FMT_III;     // TASI
            8'hE2: r = FMT_III;     // RET
            8'hE3: r = FMT_III;     // RET
            8'hE4: r = FMT_III;     // POPM
            8'hE5: r = FMT_III;     // POPM
            8'hE6: r = FMT_III;     // POP
            8'hE7: r = FMT_III;     // POP
            8'hE8: r = FMT_III;     // JSR
            8'hE9: r = FMT_III;     // JSR
            8'hEA: r = FMT_III;     // RETIU
            8'hEB: r = FMT_III;     // RETIU
            8'hEC: r = FMT_III;     // PUSHM
            8'hED: r = FMT_III;     // PUSHM
            8'hEE: r = FMT_III;     // PUSH
            8'hEF: r = FMT_III;     // PUSH
            8'hF0: r = FMT_III;     // TEST
            8'hF1: r = FMT_III;     // TEST
            8'hF2: r = FMT_III;     // TEST
            8'hF3: r = FMT_III;     // TEST
            8'hF4: r = FMT_III;     // TEST
            8'hF5: r = FMT_III;     // TEST
            8'hF6: r = FMT_III;     // GETPSW
            8'hF7: r = FMT_III;     // GETPSW
            8'hF8: r = FMT_III;     // TRAP
            8'hF9: r = FMT_III;     // TRAP
            8'hFA: r = FMT_III;     // RETIS
            8'hFB: r = FMT_III;     // RETIS
            8'hFC: r = FMT_III;     // STTASK
            8'hFD: r = FMT_III;     // STTASK
            8'hFE: r = FMT_III;     // CLRTLB
            8'hFF: r = FMT_III;     // CLRTLB
            default: r = FMT_UNKNOWN;
        endcase
        op_format_first = r;
    end
endfunction

// The escape opcodes, resolved by the subop in the base word (bits 12:8).
function automatic insn_fmt_e op_format_escape(input logic [7:0] op,
                                               input logic [4:0] subop);
    insn_fmt_e r;
    begin
        case ({op, 3'b000, subop})
            16'h5800: r = FMT_VIIA;    // CMPC
            16'h5801: r = FMT_VIIA;    // CMPCF
            16'h5802: r = FMT_VIIA;    // CMPCS
            16'h5808: r = FMT_VIIA;    // MOVC
            16'h5809: r = FMT_VIIA;    // MOVC
            16'h580A: r = FMT_VIIA;    // MOVCF
            16'h580B: r = FMT_VIIA;    // MOVCF
            16'h580C: r = FMT_VIIA;    // MOVCS
            16'h5818: r = FMT_VIIB;    // SCHC
            16'h5819: r = FMT_VIIB;    // SCHC
            16'h581A: r = FMT_VIIB;    // SKPC
            16'h581B: r = FMT_VIIB;    // SKPC
            16'h5900: r = FMT_VIIC;    // ADDDC
            16'h5901: r = FMT_VIIC;    // SUBDC
            16'h5902: r = FMT_VIIC;    // SUBRDC
            16'h5910: r = FMT_VIIC;    // CVTD.PZ
            16'h5918: r = FMT_VIIC;    // CVTD.ZP
            16'h5A00: r = FMT_VIIA;    // CMPC
            16'h5A01: r = FMT_VIIA;    // CMPCF
            16'h5A02: r = FMT_VIIA;    // CMPCS
            16'h5A08: r = FMT_VIIA;    // MOVC
            16'h5A09: r = FMT_VIIA;    // MOVC
            16'h5A0A: r = FMT_VIIA;    // MOVCF
            16'h5A0B: r = FMT_VIIA;    // MOVCF
            16'h5A0C: r = FMT_VIIA;    // MOVCS
            16'h5A18: r = FMT_VIIB;    // SCHC
            16'h5A19: r = FMT_VIIB;    // SCHC
            16'h5A1A: r = FMT_VIIB;    // SKPC
            16'h5A1B: r = FMT_VIIB;    // SKPC
            16'h5B00: r = FMT_VIIB;    // SCH0BS
            16'h5B01: r = FMT_VIIB;    // SCH0BS
            16'h5B02: r = FMT_VIIB;    // SCH1BS
            16'h5B03: r = FMT_VIIB;    // SCH1BS
            16'h5B08: r = FMT_VIIB;    // MOVBS
            16'h5B09: r = FMT_VIIB;    // MOVBS
            16'h5B0A: r = FMT_VIIB;    // NOTBS
            16'h5B0B: r = FMT_VIIB;    // NOTBS
            16'h5B10: r = FMT_VIIB;    // ANDBS
            16'h5B11: r = FMT_VIIB;    // ANDBS
            16'h5B12: r = FMT_VIIB;    // ANDNBS
            16'h5B13: r = FMT_VIIB;    // ANDNBS
            16'h5B14: r = FMT_VIIB;    // ORBS
            16'h5B15: r = FMT_VIIB;    // ORBS
            16'h5B16: r = FMT_VIIB;    // ORNBS
            16'h5B17: r = FMT_VIIB;    // ORNBS
            16'h5B18: r = FMT_VIIB;    // XORBS
            16'h5B19: r = FMT_VIIB;    // XORBS
            16'h5B1A: r = FMT_VIIB;    // XORNBS
            16'h5B1B: r = FMT_VIIB;    // XORNBS
            16'h5C00: r = FMT_II;      // CMPF
            16'h5C08: r = FMT_II;      // MOVF
            16'h5C09: r = FMT_II;      // NEGF
            16'h5C0A: r = FMT_II;      // ABSF
            16'h5C10: r = FMT_II;      // SCLF
            16'h5C18: r = FMT_II;      // ADDF
            16'h5C19: r = FMT_II;      // SUBF
            16'h5C1A: r = FMT_II;      // MULF
            16'h5C1B: r = FMT_II;      // DIVF
            16'h5D00: r = FMT_VIIB;    // CMPBF
            16'h5D01: r = FMT_VIIB;    // CMPBF
            16'h5D02: r = FMT_VIIB;    // CMPBF
            16'h5D08: r = FMT_VIIB;    // EXTBF
            16'h5D09: r = FMT_VIIB;    // EXTBF
            16'h5D0A: r = FMT_VIIB;    // EXTBF
            16'h5D18: r = FMT_VIIC;    // INSBF
            16'h5D19: r = FMT_VIIC;    // INSBF
            16'h5D1A: r = FMT_VIIC;    // INSBF
            16'h5E00: r = FMT_II;      // CMPF
            16'h5E08: r = FMT_II;      // MOVF
            16'h5E09: r = FMT_II;      // NEGF
            16'h5E0A: r = FMT_II;      // ABSF
            16'h5E10: r = FMT_II;      // SCLF
            16'h5E18: r = FMT_II;      // ADDF
            16'h5E19: r = FMT_II;      // SUBF
            16'h5E1A: r = FMT_II;      // MULF
            16'h5E1B: r = FMT_II;      // DIVF
            16'h5F00: r = FMT_II;      // CVT.WS
            16'h5F01: r = FMT_II;      // CVT.SW
            16'h5F08: r = FMT_II;      // CVTF
            16'h5F09: r = FMT_II;      // CVT.LW
            16'h5F10: r = FMT_II;      // CVT.SL
            16'h5F11: r = FMT_II;      // CVT.WL
            default: r = FMT_UNKNOWN;
        endcase
        op_format_escape = r;
    end
endfunction

// The operand's data type, as its UNIT SIZE in bytes -- the constant p.3.261
// scales an index by and steps [Rn+] by, and the width an immed.N takes
// (p.3.294 gives one mode code three rows, so the mode field cannot say).
//
// It is NOT a variable-length operand's length: that is the extension field's
// (p.3.293), and it reaches the sequencer as v60_idu's opN_ext.
//
//   0   this operand is not a datum of a width -- a displacement, a register
//       number, or an instruction with no operands
//   15  the instruction has a data operand whose width the table does not
//       carry; see tools/v60x/insn_table.py.  Callers fall back and say so.
function automatic logic [3:0] op_data_bytes_first(input logic [7:0] op,
                                                   input logic       second);
    logic [3:0] r;
    begin
        case ({op, second})
            9'h000: r = 4'd0 ;  // HALT
            9'h001: r = 4'd0 ;  // HALT (operand 2)
            9'h002: r = 4'd4 ;  // LDTASK
            9'h003: r = 4'd0 ;  // LDTASK (operand 2)
            9'h004: r = 4'd4 ;  // STPR
            9'h005: r = 4'd4 ;  // STPR (operand 2)
            9'h006: r = 4'd4 ;  // GETRA
            9'h007: r = 4'd4 ;  // GETRA (operand 2)
            9'h008: r = 4'd4 ;  // GETPTE
            9'h009: r = 4'd4 ;  // GETPTE (operand 2)
            9'h00A: r = 4'd4 ;  // GETATE
            9'h00B: r = 4'd4 ;  // GETATE (operand 2)
            9'h010: r = 4'd1 ;  // RVBIT
            9'h011: r = 4'd1 ;  // RVBIT (operand 2)
            9'h012: r = 4'd1 ;  // MOV.B
            9'h013: r = 4'd1 ;  // MOV.B (operand 2)
            9'h014: r = 4'd1 ;  // MOVS.BH
            9'h015: r = 4'd2 ;  // MOVS.BH (operand 2)
            9'h016: r = 4'd1 ;  // MOVZ.BH
            9'h017: r = 4'd2 ;  // MOVZ.BH (operand 2)
            9'h018: r = 4'd1 ;  // MOVS.BW
            9'h019: r = 4'd4 ;  // MOVS.BW (operand 2)
            9'h01A: r = 4'd1 ;  // MOVZ.BW
            9'h01B: r = 4'd4 ;  // MOVZ.BW (operand 2)
            9'h020: r = 4'd0 ;  // CLRTLBA
            9'h021: r = 4'd0 ;  // CLRTLBA (operand 2)
            9'h024: r = 4'd4 ;  // LDPR
            9'h025: r = 4'd4 ;  // LDPR (operand 2)
            9'h026: r = 4'd4 ;  // UPDPSW.W
            9'h027: r = 4'd4 ;  // UPDPSW.W (operand 2)
            9'h028: r = 4'd4 ;  // UPDPTE
            9'h029: r = 4'd4 ;  // UPDPTE (operand 2)
            9'h02A: r = 4'd4 ;  // UPDATE
            9'h02B: r = 4'd4 ;  // UPDATE (operand 2)
            9'h032: r = 4'd2 ;  // MOVT.HB
            9'h033: r = 4'd1 ;  // MOVT.HB (operand 2)
            9'h036: r = 4'd2 ;  // MOV.H
            9'h037: r = 4'd2 ;  // MOV.H (operand 2)
            9'h038: r = 4'd2 ;  // MOVS.HW
            9'h039: r = 4'd4 ;  // MOVS.HW (operand 2)
            9'h03A: r = 4'd2 ;  // MOVZ.HW
            9'h03B: r = 4'd4 ;  // MOVZ.HW (operand 2)
            9'h040: r = 4'd1 ;  // IN
            9'h041: r = 4'd1 ;  // IN (operand 2)
            9'h042: r = 4'd1 ;  // OUT
            9'h043: r = 4'd1 ;  // OUT (operand 2)
            9'h044: r = 4'd2 ;  // IN
            9'h045: r = 4'd2 ;  // IN (operand 2)
            9'h046: r = 4'd2 ;  // OUT
            9'h047: r = 4'd2 ;  // OUT (operand 2)
            9'h048: r = 4'd4 ;  // IN
            9'h049: r = 4'd4 ;  // IN (operand 2)
            9'h04A: r = 4'd4 ;  // OUT
            9'h04B: r = 4'd4 ;  // OUT (operand 2)
            9'h052: r = 4'd4 ;  // MOVT.WB
            9'h053: r = 4'd1 ;  // MOVT.WB (operand 2)
            9'h056: r = 4'd4 ;  // MOVT.WH
            9'h057: r = 4'd2 ;  // MOVT.WH (operand 2)
            9'h058: r = 4'd4 ;  // RVBYT
            9'h059: r = 4'd4 ;  // RVBYT (operand 2)
            9'h05A: r = 4'd4 ;  // MOV.W
            9'h05B: r = 4'd4 ;  // MOV.W (operand 2)
            9'h070: r = 4'd1 ;  // NOT
            9'h071: r = 4'd1 ;  // NOT (operand 2)
            9'h072: r = 4'd1 ;  // NEG
            9'h073: r = 4'd1 ;  // NEG (operand 2)
            9'h074: r = 4'd2 ;  // NOT
            9'h075: r = 4'd2 ;  // NOT (operand 2)
            9'h076: r = 4'd2 ;  // NEG
            9'h077: r = 4'd2 ;  // NEG (operand 2)
            9'h078: r = 4'd4 ;  // NOT
            9'h079: r = 4'd4 ;  // NOT (operand 2)
            9'h07A: r = 4'd4 ;  // NEG
            9'h07B: r = 4'd4 ;  // NEG (operand 2)
            9'h07E: r = 4'd8 ;  // MOV.D
            9'h07F: r = 4'd8 ;  // MOV.D (operand 2)
            9'h080: r = 4'd1 ;  // MOVEA
            9'h081: r = 4'd4 ;  // MOVEA (operand 2)
            9'h082: r = 4'd1 ;  // XCH
            9'h083: r = 4'd1 ;  // XCH (operand 2)
            9'h084: r = 4'd2 ;  // MOVEA
            9'h085: r = 4'd4 ;  // MOVEA (operand 2)
            9'h086: r = 4'd2 ;  // XCH
            9'h087: r = 4'd2 ;  // XCH (operand 2)
            9'h088: r = 4'd4 ;  // MOVEA
            9'h089: r = 4'd4 ;  // MOVEA (operand 2)
            9'h08A: r = 4'd4 ;  // XCH
            9'h08B: r = 4'd4 ;  // XCH (operand 2)
            9'h08E: r = 4'd1 ;  // SETF
            9'h08F: r = 4'd1 ;  // SETF (operand 2)
            9'h090: r = 4'd0 ;  // BSR
            9'h091: r = 4'd0 ;  // BSR (operand 2)
            9'h092: r = 4'd4 ;  // CALL
            9'h093: r = 4'd4 ;  // CALL (operand 2)
            9'h094: r = 4'd4 ;  // UPDPSW.H
            9'h095: r = 4'd4 ;  // UPDPSW.H (operand 2)
            9'h096: r = 4'd1 ;  // CHLVL
            9'h097: r = 4'd1 ;  // CHLVL (operand 2)
            9'h098: r = 4'd4 ;  // CAXI
            9'h099: r = 4'd4 ;  // CAXI (operand 2)
            9'h09A: r = 4'd4 ;  // CHKAR
            9'h09B: r = 4'd1 ;  // CHKAR (operand 2)
            9'h09C: r = 4'd4 ;  // CHKAW
            9'h09D: r = 4'd1 ;  // CHKAW (operand 2)
            9'h09E: r = 4'd4 ;  // CHKAE
            9'h09F: r = 4'd1 ;  // CHKAE (operand 2)
            9'h0A0: r = 4'd1 ;  // REM
            9'h0A1: r = 4'd1 ;  // REM (operand 2)
            9'h0A2: r = 4'd1 ;  // REMU
            9'h0A3: r = 4'd1 ;  // REMU (operand 2)
            9'h0A4: r = 4'd2 ;  // REM
            9'h0A5: r = 4'd2 ;  // REM (operand 2)
            9'h0A6: r = 4'd2 ;  // REMU
            9'h0A7: r = 4'd2 ;  // REMU (operand 2)
            9'h0A8: r = 4'd4 ;  // REM
            9'h0A9: r = 4'd4 ;  // REM (operand 2)
            9'h0AA: r = 4'd4 ;  // REMU
            9'h0AB: r = 4'd4 ;  // REMU (operand 2)
            9'h0C0: r = 4'd0 ;  // Bcc
            9'h0C1: r = 4'd0 ;  // Bcc (operand 2)
            9'h0C2: r = 4'd0 ;  // Bcc
            9'h0C3: r = 4'd0 ;  // Bcc (operand 2)
            9'h0C4: r = 4'd0 ;  // Bcc
            9'h0C5: r = 4'd0 ;  // Bcc (operand 2)
            9'h0C6: r = 4'd0 ;  // Bcc
            9'h0C7: r = 4'd0 ;  // Bcc (operand 2)
            9'h0C8: r = 4'd0 ;  // Bcc
            9'h0C9: r = 4'd0 ;  // Bcc (operand 2)
            9'h0CA: r = 4'd0 ;  // Bcc
            9'h0CB: r = 4'd0 ;  // Bcc (operand 2)
            9'h0CC: r = 4'd0 ;  // Bcc
            9'h0CD: r = 4'd0 ;  // Bcc (operand 2)
            9'h0CE: r = 4'd0 ;  // Bcc
            9'h0CF: r = 4'd0 ;  // Bcc (operand 2)
            9'h0D0: r = 4'd0 ;  // Bcc
            9'h0D1: r = 4'd0 ;  // Bcc (operand 2)
            9'h0D2: r = 4'd0 ;  // Bcc
            9'h0D3: r = 4'd0 ;  // Bcc (operand 2)
            9'h0D4: r = 4'd0 ;  // Bcc
            9'h0D5: r = 4'd0 ;  // Bcc (operand 2)
            9'h0D6: r = 4'd0 ;  // Bcc
            9'h0D7: r = 4'd0 ;  // Bcc (operand 2)
            9'h0D8: r = 4'd0 ;  // Bcc
            9'h0D9: r = 4'd0 ;  // Bcc (operand 2)
            9'h0DA: r = 4'd0 ;  // Bcc
            9'h0DB: r = 4'd0 ;  // Bcc (operand 2)
            9'h0DC: r = 4'd0 ;  // Bcc
            9'h0DD: r = 4'd0 ;  // Bcc (operand 2)
            9'h0DE: r = 4'd0 ;  // Bcc
            9'h0DF: r = 4'd0 ;  // Bcc (operand 2)
            9'h0E0: r = 4'd0 ;  // Bcc
            9'h0E1: r = 4'd0 ;  // Bcc (operand 2)
            9'h0E2: r = 4'd0 ;  // Bcc
            9'h0E3: r = 4'd0 ;  // Bcc (operand 2)
            9'h0E4: r = 4'd0 ;  // Bcc
            9'h0E5: r = 4'd0 ;  // Bcc (operand 2)
            9'h0E6: r = 4'd0 ;  // Bcc
            9'h0E7: r = 4'd0 ;  // Bcc (operand 2)
            9'h0E8: r = 4'd0 ;  // Bcc
            9'h0E9: r = 4'd0 ;  // Bcc (operand 2)
            9'h0EA: r = 4'd0 ;  // Bcc
            9'h0EB: r = 4'd0 ;  // Bcc (operand 2)
            9'h0EC: r = 4'd0 ;  // Bcc
            9'h0ED: r = 4'd0 ;  // Bcc (operand 2)
            9'h0EE: r = 4'd0 ;  // Bcc
            9'h0EF: r = 4'd0 ;  // Bcc (operand 2)
            9'h0F0: r = 4'd0 ;  // Bcc
            9'h0F1: r = 4'd0 ;  // Bcc (operand 2)
            9'h0F2: r = 4'd0 ;  // Bcc
            9'h0F3: r = 4'd0 ;  // Bcc (operand 2)
            9'h0F4: r = 4'd0 ;  // Bcc
            9'h0F5: r = 4'd0 ;  // Bcc (operand 2)
            9'h0F6: r = 4'd0 ;  // Bcc
            9'h0F7: r = 4'd0 ;  // Bcc (operand 2)
            9'h0F8: r = 4'd0 ;  // Bcc
            9'h0F9: r = 4'd0 ;  // Bcc (operand 2)
            9'h0FA: r = 4'd0 ;  // Bcc
            9'h0FB: r = 4'd0 ;  // Bcc (operand 2)
            9'h0FC: r = 4'd0 ;  // Bcc
            9'h0FD: r = 4'd0 ;  // Bcc (operand 2)
            9'h0FE: r = 4'd0 ;  // Bcc
            9'h0FF: r = 4'd0 ;  // Bcc (operand 2)
            9'h100: r = 4'd1 ;  // ADD
            9'h101: r = 4'd1 ;  // ADD (operand 2)
            9'h102: r = 4'd1 ;  // MUL
            9'h103: r = 4'd1 ;  // MUL (operand 2)
            9'h104: r = 4'd2 ;  // ADD
            9'h105: r = 4'd2 ;  // ADD (operand 2)
            9'h106: r = 4'd2 ;  // MUL
            9'h107: r = 4'd2 ;  // MUL (operand 2)
            9'h108: r = 4'd4 ;  // ADD
            9'h109: r = 4'd4 ;  // ADD (operand 2)
            9'h10A: r = 4'd4 ;  // MUL
            9'h10B: r = 4'd4 ;  // MUL (operand 2)
            9'h10C: r = 4'd4 ;  // MULX
            9'h10D: r = 4'd8 ;  // MULX (operand 2)
            9'h10E: r = 4'd4 ;  // TEST1
            9'h10F: r = 4'd4 ;  // TEST1 (operand 2)
            9'h110: r = 4'd1 ;  // OR
            9'h111: r = 4'd1 ;  // OR (operand 2)
            9'h112: r = 4'd1 ;  // ROT
            9'h113: r = 4'd1 ;  // ROT (operand 2)
            9'h114: r = 4'd2 ;  // OR
            9'h115: r = 4'd2 ;  // OR (operand 2)
            9'h116: r = 4'd1 ;  // ROT
            9'h117: r = 4'd2 ;  // ROT (operand 2)
            9'h118: r = 4'd4 ;  // OR
            9'h119: r = 4'd4 ;  // OR (operand 2)
            9'h11A: r = 4'd1 ;  // ROT
            9'h11B: r = 4'd4 ;  // ROT (operand 2)
            9'h120: r = 4'd1 ;  // ADDC
            9'h121: r = 4'd1 ;  // ADDC (operand 2)
            9'h122: r = 4'd1 ;  // MULU
            9'h123: r = 4'd1 ;  // MULU (operand 2)
            9'h124: r = 4'd2 ;  // ADDC
            9'h125: r = 4'd2 ;  // ADDC (operand 2)
            9'h126: r = 4'd2 ;  // MULU
            9'h127: r = 4'd2 ;  // MULU (operand 2)
            9'h128: r = 4'd4 ;  // ADDC
            9'h129: r = 4'd4 ;  // ADDC (operand 2)
            9'h12A: r = 4'd4 ;  // MULU
            9'h12B: r = 4'd4 ;  // MULU (operand 2)
            9'h12C: r = 4'd4 ;  // MULUX
            9'h12D: r = 4'd8 ;  // MULUX (operand 2)
            9'h12E: r = 4'd4 ;  // SET1
            9'h12F: r = 4'd4 ;  // SET1 (operand 2)
            9'h130: r = 4'd1 ;  // SUBC
            9'h131: r = 4'd1 ;  // SUBC (operand 2)
            9'h132: r = 4'd1 ;  // ROTC
            9'h133: r = 4'd1 ;  // ROTC (operand 2)
            9'h134: r = 4'd2 ;  // SUBC
            9'h135: r = 4'd2 ;  // SUBC (operand 2)
            9'h136: r = 4'd1 ;  // ROTC
            9'h137: r = 4'd2 ;  // ROTC (operand 2)
            9'h138: r = 4'd4 ;  // SUBC
            9'h139: r = 4'd4 ;  // SUBC (operand 2)
            9'h13A: r = 4'd1 ;  // ROTC
            9'h13B: r = 4'd4 ;  // ROTC (operand 2)
            9'h140: r = 4'd1 ;  // AND
            9'h141: r = 4'd1 ;  // AND (operand 2)
            9'h142: r = 4'd1 ;  // DIV
            9'h143: r = 4'd1 ;  // DIV (operand 2)
            9'h144: r = 4'd2 ;  // AND
            9'h145: r = 4'd2 ;  // AND (operand 2)
            9'h146: r = 4'd2 ;  // DIV
            9'h147: r = 4'd2 ;  // DIV (operand 2)
            9'h148: r = 4'd4 ;  // AND
            9'h149: r = 4'd4 ;  // AND (operand 2)
            9'h14A: r = 4'd4 ;  // DIV
            9'h14B: r = 4'd4 ;  // DIV (operand 2)
            9'h14C: r = 4'd4 ;  // DIVX
            9'h14D: r = 4'd8 ;  // DIVX (operand 2)
            9'h14E: r = 4'd4 ;  // CLR1
            9'h14F: r = 4'd4 ;  // CLR1 (operand 2)
            9'h150: r = 4'd1 ;  // SUB
            9'h151: r = 4'd1 ;  // SUB (operand 2)
            9'h152: r = 4'd1 ;  // SHL
            9'h153: r = 4'd1 ;  // SHL (operand 2)
            9'h154: r = 4'd2 ;  // SUB
            9'h155: r = 4'd2 ;  // SUB (operand 2)
            9'h156: r = 4'd1 ;  // SHL
            9'h157: r = 4'd2 ;  // SHL (operand 2)
            9'h158: r = 4'd4 ;  // SUB
            9'h159: r = 4'd4 ;  // SUB (operand 2)
            9'h15A: r = 4'd1 ;  // SHL
            9'h15B: r = 4'd4 ;  // SHL (operand 2)
            9'h160: r = 4'd1 ;  // XOR
            9'h161: r = 4'd1 ;  // XOR (operand 2)
            9'h162: r = 4'd1 ;  // DIVU
            9'h163: r = 4'd1 ;  // DIVU (operand 2)
            9'h164: r = 4'd2 ;  // XOR
            9'h165: r = 4'd2 ;  // XOR (operand 2)
            9'h166: r = 4'd2 ;  // DIVU
            9'h167: r = 4'd2 ;  // DIVU (operand 2)
            9'h168: r = 4'd4 ;  // XOR
            9'h169: r = 4'd4 ;  // XOR (operand 2)
            9'h16A: r = 4'd4 ;  // DIVU
            9'h16B: r = 4'd4 ;  // DIVU (operand 2)
            9'h16C: r = 4'd4 ;  // DIVUX
            9'h16D: r = 4'd8 ;  // DIVUX (operand 2)
            9'h16E: r = 4'd4 ;  // NOT1
            9'h16F: r = 4'd4 ;  // NOT1 (operand 2)
            9'h170: r = 4'd1 ;  // CMP
            9'h171: r = 4'd1 ;  // CMP (operand 2)
            9'h172: r = 4'd1 ;  // SHA
            9'h173: r = 4'd1 ;  // SHA (operand 2)
            9'h174: r = 4'd2 ;  // CMP
            9'h175: r = 4'd2 ;  // CMP (operand 2)
            9'h176: r = 4'd1 ;  // SHA
            9'h177: r = 4'd2 ;  // SHA (operand 2)
            9'h178: r = 4'd4 ;  // CMP
            9'h179: r = 4'd4 ;  // CMP (operand 2)
            9'h17A: r = 4'd1 ;  // SHA
            9'h17B: r = 4'd4 ;  // SHA (operand 2)
            9'h18C: r = 4'd0 ;  // DBcc
            9'h18D: r = 4'd0 ;  // DBcc (operand 2)
            9'h18E: r = 4'd0 ;  // TB
            9'h18F: r = 4'd0 ;  // TB (operand 2)
            9'h190: r = 4'd0 ;  // BRK
            9'h191: r = 4'd0 ;  // BRK (operand 2)
            9'h192: r = 4'd0 ;  // BRKV
            9'h193: r = 4'd0 ;  // BRKV (operand 2)
            9'h194: r = 4'd0 ;  // RSR
            9'h195: r = 4'd0 ;  // RSR (operand 2)
            9'h196: r = 4'd0 ;  // TRAPFL
            9'h197: r = 4'd0 ;  // TRAPFL (operand 2)
            9'h198: r = 4'd0 ;  // DISPOSE
            9'h199: r = 4'd0 ;  // DISPOSE (operand 2)
            9'h19A: r = 4'd0 ;  // NOP
            9'h19B: r = 4'd0 ;  // NOP (operand 2)
            9'h1A0: r = 4'd1 ;  // DEC
            9'h1A1: r = 4'd0 ;  // DEC (operand 2)
            9'h1A2: r = 4'd1 ;  // DEC
            9'h1A3: r = 4'd0 ;  // DEC (operand 2)
            9'h1A4: r = 4'd2 ;  // DEC
            9'h1A5: r = 4'd0 ;  // DEC (operand 2)
            9'h1A6: r = 4'd2 ;  // DEC
            9'h1A7: r = 4'd0 ;  // DEC (operand 2)
            9'h1A8: r = 4'd4 ;  // DEC
            9'h1A9: r = 4'd0 ;  // DEC (operand 2)
            9'h1AA: r = 4'd4 ;  // DEC
            9'h1AB: r = 4'd0 ;  // DEC (operand 2)
            9'h1AC: r = 4'd4 ;  // JMP
            9'h1AD: r = 4'd0 ;  // JMP (operand 2)
            9'h1AE: r = 4'd4 ;  // JMP
            9'h1AF: r = 4'd0 ;  // JMP (operand 2)
            9'h1B0: r = 4'd1 ;  // INC
            9'h1B1: r = 4'd0 ;  // INC (operand 2)
            9'h1B2: r = 4'd1 ;  // INC
            9'h1B3: r = 4'd0 ;  // INC (operand 2)
            9'h1B4: r = 4'd2 ;  // INC
            9'h1B5: r = 4'd0 ;  // INC (operand 2)
            9'h1B6: r = 4'd2 ;  // INC
            9'h1B7: r = 4'd0 ;  // INC (operand 2)
            9'h1B8: r = 4'd4 ;  // INC
            9'h1B9: r = 4'd0 ;  // INC (operand 2)
            9'h1BA: r = 4'd4 ;  // INC
            9'h1BB: r = 4'd0 ;  // INC (operand 2)
            9'h1BC: r = 4'd4 ;  // PREPARE
            9'h1BD: r = 4'd0 ;  // PREPARE (operand 2)
            9'h1BE: r = 4'd4 ;  // PREPARE
            9'h1BF: r = 4'd0 ;  // PREPARE (operand 2)
            9'h1C0: r = 4'd1 ;  // TASI
            9'h1C1: r = 4'd0 ;  // TASI (operand 2)
            9'h1C2: r = 4'd1 ;  // TASI
            9'h1C3: r = 4'd0 ;  // TASI (operand 2)
            9'h1C4: r = 4'd4 ;  // RET
            9'h1C5: r = 4'd0 ;  // RET (operand 2)
            9'h1C6: r = 4'd4 ;  // RET
            9'h1C7: r = 4'd0 ;  // RET (operand 2)
            9'h1C8: r = 4'd4 ;  // POPM
            9'h1C9: r = 4'd0 ;  // POPM (operand 2)
            9'h1CA: r = 4'd4 ;  // POPM
            9'h1CB: r = 4'd0 ;  // POPM (operand 2)
            9'h1CC: r = 4'd4 ;  // POP
            9'h1CD: r = 4'd0 ;  // POP (operand 2)
            9'h1CE: r = 4'd4 ;  // POP
            9'h1CF: r = 4'd0 ;  // POP (operand 2)
            9'h1D0: r = 4'd4 ;  // JSR
            9'h1D1: r = 4'd0 ;  // JSR (operand 2)
            9'h1D2: r = 4'd4 ;  // JSR
            9'h1D3: r = 4'd0 ;  // JSR (operand 2)
            9'h1D4: r = 4'd2 ;  // RETIU
            9'h1D5: r = 4'd0 ;  // RETIU (operand 2)
            9'h1D6: r = 4'd2 ;  // RETIU
            9'h1D7: r = 4'd0 ;  // RETIU (operand 2)
            9'h1D8: r = 4'd4 ;  // PUSHM
            9'h1D9: r = 4'd0 ;  // PUSHM (operand 2)
            9'h1DA: r = 4'd4 ;  // PUSHM
            9'h1DB: r = 4'd0 ;  // PUSHM (operand 2)
            9'h1DC: r = 4'd4 ;  // PUSH
            9'h1DD: r = 4'd0 ;  // PUSH (operand 2)
            9'h1DE: r = 4'd4 ;  // PUSH
            9'h1DF: r = 4'd0 ;  // PUSH (operand 2)
            9'h1E0: r = 4'd1 ;  // TEST
            9'h1E1: r = 4'd0 ;  // TEST (operand 2)
            9'h1E2: r = 4'd1 ;  // TEST
            9'h1E3: r = 4'd0 ;  // TEST (operand 2)
            9'h1E4: r = 4'd2 ;  // TEST
            9'h1E5: r = 4'd0 ;  // TEST (operand 2)
            9'h1E6: r = 4'd2 ;  // TEST
            9'h1E7: r = 4'd0 ;  // TEST (operand 2)
            9'h1E8: r = 4'd4 ;  // TEST
            9'h1E9: r = 4'd0 ;  // TEST (operand 2)
            9'h1EA: r = 4'd4 ;  // TEST
            9'h1EB: r = 4'd0 ;  // TEST (operand 2)
            9'h1EC: r = 4'd4 ;  // GETPSW
            9'h1ED: r = 4'd0 ;  // GETPSW (operand 2)
            9'h1EE: r = 4'd4 ;  // GETPSW
            9'h1EF: r = 4'd0 ;  // GETPSW (operand 2)
            9'h1F0: r = 4'd1 ;  // TRAP
            9'h1F1: r = 4'd0 ;  // TRAP (operand 2)
            9'h1F2: r = 4'd1 ;  // TRAP
            9'h1F3: r = 4'd0 ;  // TRAP (operand 2)
            9'h1F4: r = 4'd2 ;  // RETIS
            9'h1F5: r = 4'd0 ;  // RETIS (operand 2)
            9'h1F6: r = 4'd2 ;  // RETIS
            9'h1F7: r = 4'd0 ;  // RETIS (operand 2)
            9'h1F8: r = 4'd4 ;  // STTASK
            9'h1F9: r = 4'd0 ;  // STTASK (operand 2)
            9'h1FA: r = 4'd4 ;  // STTASK
            9'h1FB: r = 4'd0 ;  // STTASK (operand 2)
            9'h1FC: r = 4'd4 ;  // CLRTLB
            9'h1FD: r = 4'd0 ;  // CLRTLB (operand 2)
            9'h1FE: r = 4'd4 ;  // CLRTLB
            9'h1FF: r = 4'd0 ;  // CLRTLB (operand 2)
            default: r = 4'd15;    // not an instruction: nothing to say
        endcase
        op_data_bytes_first = r;
    end
endfunction

// The escape opcodes again: 5C and 5E carry MOVF and SCLF alike, and their
// first operands are not the same kind of thing, so the width is keyed by the
// subop exactly as the format is.
function automatic logic [3:0] op_data_bytes_escape(input logic [7:0] op,
                                                    input logic [4:0] subop,
                                                    input logic       second);
    logic [3:0] r;
    begin
        case ({op, 2'b00, subop, second})
            16'h5800: r = 4'd1 ;  // CMPC
            16'h5801: r = 4'd1 ;  // CMPC (operand 2)
            16'h5802: r = 4'd1 ;  // CMPCF
            16'h5803: r = 4'd1 ;  // CMPCF (operand 2)
            16'h5804: r = 4'd1 ;  // CMPCS
            16'h5805: r = 4'd1 ;  // CMPCS (operand 2)
            16'h5810: r = 4'd1 ;  // MOVC
            16'h5811: r = 4'd1 ;  // MOVC (operand 2)
            16'h5812: r = 4'd1 ;  // MOVC
            16'h5813: r = 4'd1 ;  // MOVC (operand 2)
            16'h5814: r = 4'd1 ;  // MOVCF
            16'h5815: r = 4'd1 ;  // MOVCF (operand 2)
            16'h5816: r = 4'd1 ;  // MOVCF
            16'h5817: r = 4'd1 ;  // MOVCF (operand 2)
            16'h5818: r = 4'd1 ;  // MOVCS
            16'h5819: r = 4'd1 ;  // MOVCS (operand 2)
            16'h5830: r = 4'd1 ;  // SCHC
            16'h5831: r = 4'd1 ;  // SCHC (operand 2)
            16'h5832: r = 4'd1 ;  // SCHC
            16'h5833: r = 4'd1 ;  // SCHC (operand 2)
            16'h5834: r = 4'd1 ;  // SKPC
            16'h5835: r = 4'd1 ;  // SKPC (operand 2)
            16'h5836: r = 4'd1 ;  // SKPC
            16'h5837: r = 4'd1 ;  // SKPC (operand 2)
            16'h5900: r = 4'd1 ;  // ADDDC
            16'h5901: r = 4'd1 ;  // ADDDC (operand 2)
            16'h5902: r = 4'd1 ;  // SUBDC
            16'h5903: r = 4'd1 ;  // SUBDC (operand 2)
            16'h5904: r = 4'd1 ;  // SUBRDC
            16'h5905: r = 4'd1 ;  // SUBRDC (operand 2)
            16'h5920: r = 4'd1 ;  // CVTD.PZ
            16'h5921: r = 4'd2 ;  // CVTD.PZ (operand 2)
            16'h5930: r = 4'd2 ;  // CVTD.ZP
            16'h5931: r = 4'd1 ;  // CVTD.ZP (operand 2)
            16'h5A00: r = 4'd2 ;  // CMPC
            16'h5A01: r = 4'd2 ;  // CMPC (operand 2)
            16'h5A02: r = 4'd2 ;  // CMPCF
            16'h5A03: r = 4'd2 ;  // CMPCF (operand 2)
            16'h5A04: r = 4'd2 ;  // CMPCS
            16'h5A05: r = 4'd2 ;  // CMPCS (operand 2)
            16'h5A10: r = 4'd2 ;  // MOVC
            16'h5A11: r = 4'd2 ;  // MOVC (operand 2)
            16'h5A12: r = 4'd2 ;  // MOVC
            16'h5A13: r = 4'd2 ;  // MOVC (operand 2)
            16'h5A14: r = 4'd2 ;  // MOVCF
            16'h5A15: r = 4'd2 ;  // MOVCF (operand 2)
            16'h5A16: r = 4'd2 ;  // MOVCF
            16'h5A17: r = 4'd2 ;  // MOVCF (operand 2)
            16'h5A18: r = 4'd2 ;  // MOVCS
            16'h5A19: r = 4'd2 ;  // MOVCS (operand 2)
            16'h5A30: r = 4'd2 ;  // SCHC
            16'h5A31: r = 4'd2 ;  // SCHC (operand 2)
            16'h5A32: r = 4'd2 ;  // SCHC
            16'h5A33: r = 4'd2 ;  // SCHC (operand 2)
            16'h5A34: r = 4'd2 ;  // SKPC
            16'h5A35: r = 4'd2 ;  // SKPC (operand 2)
            16'h5A36: r = 4'd2 ;  // SKPC
            16'h5A37: r = 4'd2 ;  // SKPC (operand 2)
            16'h5B00: r = 4'd4 ;  // SCH0BS
            16'h5B01: r = 4'd4 ;  // SCH0BS (operand 2)
            16'h5B02: r = 4'd4 ;  // SCH0BS
            16'h5B03: r = 4'd4 ;  // SCH0BS (operand 2)
            16'h5B04: r = 4'd4 ;  // SCH1BS
            16'h5B05: r = 4'd4 ;  // SCH1BS (operand 2)
            16'h5B06: r = 4'd4 ;  // SCH1BS
            16'h5B07: r = 4'd4 ;  // SCH1BS (operand 2)
            16'h5B10: r = 4'd4 ;  // MOVBS
            16'h5B11: r = 4'd4 ;  // MOVBS (operand 2)
            16'h5B12: r = 4'd4 ;  // MOVBS
            16'h5B13: r = 4'd4 ;  // MOVBS (operand 2)
            16'h5B14: r = 4'd4 ;  // NOTBS
            16'h5B15: r = 4'd4 ;  // NOTBS (operand 2)
            16'h5B16: r = 4'd4 ;  // NOTBS
            16'h5B17: r = 4'd4 ;  // NOTBS (operand 2)
            16'h5B20: r = 4'd4 ;  // ANDBS
            16'h5B21: r = 4'd4 ;  // ANDBS (operand 2)
            16'h5B22: r = 4'd4 ;  // ANDBS
            16'h5B23: r = 4'd4 ;  // ANDBS (operand 2)
            16'h5B24: r = 4'd4 ;  // ANDNBS
            16'h5B25: r = 4'd4 ;  // ANDNBS (operand 2)
            16'h5B26: r = 4'd4 ;  // ANDNBS
            16'h5B27: r = 4'd4 ;  // ANDNBS (operand 2)
            16'h5B28: r = 4'd4 ;  // ORBS
            16'h5B29: r = 4'd4 ;  // ORBS (operand 2)
            16'h5B2A: r = 4'd4 ;  // ORBS
            16'h5B2B: r = 4'd4 ;  // ORBS (operand 2)
            16'h5B2C: r = 4'd4 ;  // ORNBS
            16'h5B2D: r = 4'd4 ;  // ORNBS (operand 2)
            16'h5B2E: r = 4'd4 ;  // ORNBS
            16'h5B2F: r = 4'd4 ;  // ORNBS (operand 2)
            16'h5B30: r = 4'd4 ;  // XORBS
            16'h5B31: r = 4'd4 ;  // XORBS (operand 2)
            16'h5B32: r = 4'd4 ;  // XORBS
            16'h5B33: r = 4'd4 ;  // XORBS (operand 2)
            16'h5B34: r = 4'd4 ;  // XORNBS
            16'h5B35: r = 4'd4 ;  // XORNBS (operand 2)
            16'h5B36: r = 4'd4 ;  // XORNBS
            16'h5B37: r = 4'd4 ;  // XORNBS (operand 2)
            16'h5C00: r = 4'd4 ;  // CMPF
            16'h5C01: r = 4'd4 ;  // CMPF (operand 2)
            16'h5C10: r = 4'd4 ;  // MOVF
            16'h5C11: r = 4'd4 ;  // MOVF (operand 2)
            16'h5C12: r = 4'd4 ;  // NEGF
            16'h5C13: r = 4'd4 ;  // NEGF (operand 2)
            16'h5C14: r = 4'd4 ;  // ABSF
            16'h5C15: r = 4'd4 ;  // ABSF (operand 2)
            16'h5C20: r = 4'd4 ;  // SCLF
            16'h5C21: r = 4'd4 ;  // SCLF (operand 2)
            16'h5C30: r = 4'd4 ;  // ADDF
            16'h5C31: r = 4'd4 ;  // ADDF (operand 2)
            16'h5C32: r = 4'd4 ;  // SUBF
            16'h5C33: r = 4'd4 ;  // SUBF (operand 2)
            16'h5C34: r = 4'd4 ;  // MULF
            16'h5C35: r = 4'd4 ;  // MULF (operand 2)
            16'h5C36: r = 4'd4 ;  // DIVF
            16'h5C37: r = 4'd4 ;  // DIVF (operand 2)
            16'h5D00: r = 4'd4 ;  // CMPBF
            16'h5D01: r = 4'd4 ;  // CMPBF (operand 2)
            16'h5D02: r = 4'd4 ;  // CMPBF
            16'h5D03: r = 4'd4 ;  // CMPBF (operand 2)
            16'h5D04: r = 4'd4 ;  // CMPBF
            16'h5D05: r = 4'd4 ;  // CMPBF (operand 2)
            16'h5D10: r = 4'd4 ;  // EXTBF
            16'h5D11: r = 4'd4 ;  // EXTBF (operand 2)
            16'h5D12: r = 4'd4 ;  // EXTBF
            16'h5D13: r = 4'd4 ;  // EXTBF (operand 2)
            16'h5D14: r = 4'd4 ;  // EXTBF
            16'h5D15: r = 4'd4 ;  // EXTBF (operand 2)
            16'h5D30: r = 4'd4 ;  // INSBF
            16'h5D31: r = 4'd4 ;  // INSBF (operand 2)
            16'h5D32: r = 4'd4 ;  // INSBF
            16'h5D33: r = 4'd4 ;  // INSBF (operand 2)
            16'h5D34: r = 4'd4 ;  // INSBF
            16'h5D35: r = 4'd4 ;  // INSBF (operand 2)
            16'h5E00: r = 4'd8 ;  // CMPF
            16'h5E01: r = 4'd8 ;  // CMPF (operand 2)
            16'h5E10: r = 4'd8 ;  // MOVF
            16'h5E11: r = 4'd8 ;  // MOVF (operand 2)
            16'h5E12: r = 4'd8 ;  // NEGF
            16'h5E13: r = 4'd8 ;  // NEGF (operand 2)
            16'h5E14: r = 4'd8 ;  // ABSF
            16'h5E15: r = 4'd8 ;  // ABSF (operand 2)
            16'h5E20: r = 4'd4 ;  // SCLF
            16'h5E21: r = 4'd8 ;  // SCLF (operand 2)
            16'h5E30: r = 4'd8 ;  // ADDF
            16'h5E31: r = 4'd8 ;  // ADDF (operand 2)
            16'h5E32: r = 4'd8 ;  // SUBF
            16'h5E33: r = 4'd8 ;  // SUBF (operand 2)
            16'h5E34: r = 4'd8 ;  // MULF
            16'h5E35: r = 4'd8 ;  // MULF (operand 2)
            16'h5E36: r = 4'd8 ;  // DIVF
            16'h5E37: r = 4'd8 ;  // DIVF (operand 2)
            16'h5F00: r = 4'd4 ;  // CVT.WS
            16'h5F01: r = 4'd4 ;  // CVT.WS (operand 2)
            16'h5F02: r = 4'd4 ;  // CVT.SW
            16'h5F03: r = 4'd4 ;  // CVT.SW (operand 2)
            16'h5F10: r = 4'd8 ;  // CVTF
            16'h5F11: r = 4'd4 ;  // CVTF (operand 2)
            16'h5F12: r = 4'd8 ;  // CVT.LW
            16'h5F13: r = 4'd4 ;  // CVT.LW (operand 2)
            16'h5F20: r = 4'd4 ;  // CVT.SL
            16'h5F21: r = 4'd8 ;  // CVT.SL (operand 2)
            16'h5F22: r = 4'd4 ;  // CVT.WL
            16'h5F23: r = 4'd8 ;  // CVT.WL (operand 2)
            default: r = 4'd15;
        endcase
        op_data_bytes_escape = r;
    end
endfunction

// The whole answer.  `subop` is the base word's, and is ignored unless the
// opcode is one of the escapes.
function automatic logic [3:0] op_data_bytes(input logic [7:0] op,
                                             input logic [4:0] subop,
                                             input logic       second);
    logic [3:0] r;
    begin
        if (op_format_first(op) == FMT_ESCAPE)
            r = op_data_bytes_escape(op, subop, second);
        else
            r = op_data_bytes_first(op, second);
        op_data_bytes = r;
    end
endfunction

// What the instruction does, for the ones v60_alu implements.  ALU_NONE means
// the sequencer can decode and address it but not execute it.
function automatic alu_op_e op_alu(input logic [7:0] op);
    alu_op_e r;
    begin
        case (op)
            8'h00: r = ALU_HALT; // HALT
            8'h02: r = ALU_STPR; // STPR
            8'h08: r = ALU_RVBIT; // RVBIT
            8'h09: r = ALU_MOV;  // MOV.B
            8'h0A: r = ALU_MOVS; // MOVS.BH
            8'h0B: r = ALU_MOVZ; // MOVZ.BH
            8'h0C: r = ALU_MOVS; // MOVS.BW
            8'h0D: r = ALU_MOVZ; // MOVZ.BW
            8'h12: r = ALU_LDPR; // LDPR
            8'h13: r = ALU_UPDPSWW; // UPDPSW.W
            8'h19: r = ALU_MOVT; // MOVT.HB
            8'h1B: r = ALU_MOV;  // MOV.H
            8'h1C: r = ALU_MOVS; // MOVS.HW
            8'h1D: r = ALU_MOVZ; // MOVZ.HW
            8'h20: r = ALU_IN;   // IN
            8'h21: r = ALU_OUT;  // OUT
            8'h22: r = ALU_IN;   // IN
            8'h23: r = ALU_OUT;  // OUT
            8'h24: r = ALU_IN;   // IN
            8'h25: r = ALU_OUT;  // OUT
            8'h29: r = ALU_MOVT; // MOVT.WB
            8'h2B: r = ALU_MOVT; // MOVT.WH
            8'h2C: r = ALU_RVBYT; // RVBYT
            8'h2D: r = ALU_MOV;  // MOV.W
            8'h38: r = ALU_NOT;  // NOT
            8'h39: r = ALU_NEG;  // NEG
            8'h3A: r = ALU_NOT;  // NOT
            8'h3B: r = ALU_NEG;  // NEG
            8'h3C: r = ALU_NOT;  // NOT
            8'h3D: r = ALU_NEG;  // NEG
            8'h3F: r = ALU_MOV;  // MOV.D
            8'h40: r = ALU_MOVEA; // MOVEA
            8'h41: r = ALU_XCH;  // XCH
            8'h42: r = ALU_MOVEA; // MOVEA
            8'h43: r = ALU_XCH;  // XCH
            8'h44: r = ALU_MOVEA; // MOVEA
            8'h45: r = ALU_XCH;  // XCH
            8'h47: r = ALU_SETF; // SETF
            8'h4A: r = ALU_UPDPSWH; // UPDPSW.H
            8'h4B: r = ALU_CHLVL; // CHLVL
            8'h4C: r = ALU_CAXI; // CAXI
            8'h50: r = ALU_REM;  // REM
            8'h51: r = ALU_REMU; // REMU
            8'h52: r = ALU_REM;  // REM
            8'h53: r = ALU_REMU; // REMU
            8'h54: r = ALU_REM;  // REM
            8'h55: r = ALU_REMU; // REMU
            8'h80: r = ALU_ADD;  // ADD
            8'h81: r = ALU_MUL;  // MUL
            8'h82: r = ALU_ADD;  // ADD
            8'h83: r = ALU_MUL;  // MUL
            8'h84: r = ALU_ADD;  // ADD
            8'h85: r = ALU_MUL;  // MUL
            8'h86: r = ALU_MULX; // MULX
            8'h87: r = ALU_TEST1; // TEST1
            8'h88: r = ALU_OR;   // OR
            8'h89: r = ALU_ROT;  // ROT
            8'h8A: r = ALU_OR;   // OR
            8'h8B: r = ALU_ROT;  // ROT
            8'h8C: r = ALU_OR;   // OR
            8'h8D: r = ALU_ROT;  // ROT
            8'h90: r = ALU_ADDC; // ADDC
            8'h91: r = ALU_MULU; // MULU
            8'h92: r = ALU_ADDC; // ADDC
            8'h93: r = ALU_MULU; // MULU
            8'h94: r = ALU_ADDC; // ADDC
            8'h95: r = ALU_MULU; // MULU
            8'h96: r = ALU_MULUX; // MULUX
            8'h97: r = ALU_SET1; // SET1
            8'h98: r = ALU_SUBC; // SUBC
            8'h99: r = ALU_ROTC; // ROTC
            8'h9A: r = ALU_SUBC; // SUBC
            8'h9B: r = ALU_ROTC; // ROTC
            8'h9C: r = ALU_SUBC; // SUBC
            8'h9D: r = ALU_ROTC; // ROTC
            8'hA0: r = ALU_AND;  // AND
            8'hA1: r = ALU_DIV;  // DIV
            8'hA2: r = ALU_AND;  // AND
            8'hA3: r = ALU_DIV;  // DIV
            8'hA4: r = ALU_AND;  // AND
            8'hA5: r = ALU_DIV;  // DIV
            8'hA6: r = ALU_DIVX; // DIVX
            8'hA7: r = ALU_CLR1; // CLR1
            8'hA8: r = ALU_SUB;  // SUB
            8'hA9: r = ALU_SHL;  // SHL
            8'hAA: r = ALU_SUB;  // SUB
            8'hAB: r = ALU_SHL;  // SHL
            8'hAC: r = ALU_SUB;  // SUB
            8'hAD: r = ALU_SHL;  // SHL
            8'hB0: r = ALU_XOR;  // XOR
            8'hB1: r = ALU_DIVU; // DIVU
            8'hB2: r = ALU_XOR;  // XOR
            8'hB3: r = ALU_DIVU; // DIVU
            8'hB4: r = ALU_XOR;  // XOR
            8'hB5: r = ALU_DIVU; // DIVU
            8'hB6: r = ALU_DIVUX; // DIVUX
            8'hB7: r = ALU_NOT1; // NOT1
            8'hB8: r = ALU_CMP;  // CMP
            8'hB9: r = ALU_SHA;  // SHA
            8'hBA: r = ALU_CMP;  // CMP
            8'hBB: r = ALU_SHA;  // SHA
            8'hBC: r = ALU_CMP;  // CMP
            8'hBD: r = ALU_SHA;  // SHA
            8'hC8: r = ALU_BRK;  // BRK
            8'hC9: r = ALU_BRKV; // BRKV
            8'hCB: r = ALU_TRAPFL; // TRAPFL
            8'hCC: r = ALU_DISPOSE; // DISPOSE
            8'hCD: r = ALU_NOP;  // NOP
            8'hD0: r = ALU_DEC;  // DEC
            8'hD1: r = ALU_DEC;  // DEC
            8'hD2: r = ALU_DEC;  // DEC
            8'hD3: r = ALU_DEC;  // DEC
            8'hD4: r = ALU_DEC;  // DEC
            8'hD5: r = ALU_DEC;  // DEC
            8'hD8: r = ALU_INC;  // INC
            8'hD9: r = ALU_INC;  // INC
            8'hDA: r = ALU_INC;  // INC
            8'hDB: r = ALU_INC;  // INC
            8'hDC: r = ALU_INC;  // INC
            8'hDD: r = ALU_INC;  // INC
            8'hDE: r = ALU_PREPARE; // PREPARE
            8'hDF: r = ALU_PREPARE; // PREPARE
            8'hE0: r = ALU_TASI; // TASI
            8'hE1: r = ALU_TASI; // TASI
            8'hE4: r = ALU_POPM; // POPM
            8'hE5: r = ALU_POPM; // POPM
            8'hE6: r = ALU_POP;  // POP
            8'hE7: r = ALU_POP;  // POP
            8'hEC: r = ALU_PUSHM; // PUSHM
            8'hED: r = ALU_PUSHM; // PUSHM
            8'hEE: r = ALU_PUSH; // PUSH
            8'hEF: r = ALU_PUSH; // PUSH
            8'hF0: r = ALU_TEST; // TEST
            8'hF1: r = ALU_TEST; // TEST
            8'hF2: r = ALU_TEST; // TEST
            8'hF3: r = ALU_TEST; // TEST
            8'hF4: r = ALU_TEST; // TEST
            8'hF5: r = ALU_TEST; // TEST
            8'hF6: r = ALU_GETPSW; // GETPSW
            8'hF7: r = ALU_GETPSW; // GETPSW
            8'hF8: r = ALU_TRAP; // TRAP
            8'hF9: r = ALU_TRAP; // TRAP
            default: r = ALU_NONE;
        endcase
        op_alu = r;
    end
endfunction

// Which control transfer an opcode is, if any.
function automatic ctrl_op_e op_ctrl(input logic [7:0] op);
    ctrl_op_e r;
    begin
        case (op)
            8'h48: r = CTRL_BSR;  // BSR
            8'h49: r = CTRL_CALL; // CALL
            8'h60: r = CTRL_BCC;  // Bcc
            8'h61: r = CTRL_BCC;  // Bcc
            8'h62: r = CTRL_BCC;  // Bcc
            8'h63: r = CTRL_BCC;  // Bcc
            8'h64: r = CTRL_BCC;  // Bcc
            8'h65: r = CTRL_BCC;  // Bcc
            8'h66: r = CTRL_BCC;  // Bcc
            8'h67: r = CTRL_BCC;  // Bcc
            8'h68: r = CTRL_BCC;  // Bcc
            8'h69: r = CTRL_BCC;  // Bcc
            8'h6A: r = CTRL_BCC;  // Bcc
            8'h6B: r = CTRL_BCC;  // Bcc
            8'h6C: r = CTRL_BCC;  // Bcc
            8'h6D: r = CTRL_BCC;  // Bcc
            8'h6E: r = CTRL_BCC;  // Bcc
            8'h6F: r = CTRL_BCC;  // Bcc
            8'h70: r = CTRL_BCC;  // Bcc
            8'h71: r = CTRL_BCC;  // Bcc
            8'h72: r = CTRL_BCC;  // Bcc
            8'h73: r = CTRL_BCC;  // Bcc
            8'h74: r = CTRL_BCC;  // Bcc
            8'h75: r = CTRL_BCC;  // Bcc
            8'h76: r = CTRL_BCC;  // Bcc
            8'h77: r = CTRL_BCC;  // Bcc
            8'h78: r = CTRL_BCC;  // Bcc
            8'h79: r = CTRL_BCC;  // Bcc
            8'h7A: r = CTRL_BCC;  // Bcc
            8'h7B: r = CTRL_BCC;  // Bcc
            8'h7C: r = CTRL_BCC;  // Bcc
            8'h7D: r = CTRL_BCC;  // Bcc
            8'h7E: r = CTRL_BCC;  // Bcc
            8'h7F: r = CTRL_BCC;  // Bcc
            8'hC6: r = CTRL_DBCC; // DBcc
            8'hC7: r = CTRL_TB;   // TB
            8'hCA: r = CTRL_RSR;  // RSR
            8'hD6: r = CTRL_JMP;  // JMP
            8'hD7: r = CTRL_JMP;  // JMP
            8'hE2: r = CTRL_RET;  // RET
            8'hE3: r = CTRL_RET;  // RET
            8'hE8: r = CTRL_JSR;  // JSR
            8'hE9: r = CTRL_JSR;  // JSR
            8'hEA: r = CTRL_RETIU; // RETIU
            8'hEB: r = CTRL_RETIU; // RETIU
            8'hFA: r = CTRL_RETIS; // RETIS
            8'hFB: r = CTRL_RETIS; // RETIS
            default: r = CTRL_NONE;
        endcase
        op_ctrl = r;
    end
endfunction

// Format IV's displacement width, which is in the opcode and in two
// documents.  The databook prints Bcc as `011 b cccc` with the branch
// displacement table on p.3.295 giving "b = 0 byte / b = 1 halfword"; the
// Programmer's Reference S7 page for Bcc prints "Branch on Condition (byte
// displacement) 6x / (halfword displacement) 7x", and its BSR page prints the
// syntax as "bsr disp16".  Those are the only two Format IV opcodes.
function automatic logic [1:0] op_iv_disp_bytes(input logic [7:0] op);
    logic [1:0] r;
    begin
        case (op[7:4])
            4'h6:    r = 2'd1;   // Bcc, byte displacement
            4'h7:    r = 2'd2;   // Bcc, halfword displacement
            default: r = 2'd2;   // BSR: "bsr disp16"
        endcase
        op_iv_disp_bytes = r;
    end
endfunction

// The whole answer, given the opcode byte and the byte after it.  For a
// format with no second byte the second argument is ignored.
function automatic insn_fmt_e op_format(input logic [7:0] op,
                                        input logic [7:0] second);
    insn_fmt_e f;
    begin
        f = op_format_first(op);
        if (f == FMT_I_OR_II) begin
            if (second[7]) f = FMT_II;
            else           f = FMT_I;
        end else if (f == FMT_ESCAPE) begin
            f = op_format_escape(op, second[4:0]);
        end
        op_format = f;
    end
endfunction

endpackage

`endif
