//============================================================================
//  v60_op_pkg -- which instruction format an opcode is.
//
//  GENERATED by tools/v60x/gen_op_pkg.py from tools/v60x/insn_table.py.
//  Do not edit: edit the table and regenerate.  verif/v60x/run_v60x.sh checks
//  that this file matches its source.
//
//  Source: NEC_uPD70616_V60_DataBook_1986.pdf pp.3.296-3.299, the instruction
//  set summary's "Instruction Format" column, cross-checked where it can be
//  against the Programmer's Reference.  docs/v60/INSTRUCTION-FORMATS.md
//  carries the traps; tools/v60x/insn_table.py carries the table, the
//  placeholder-field expansion, the collision check and the two places the two
//  NEC documents disagree.
//
//  Three answers are possible for one opcode byte:
//
//    a format          the opcode says, on its own
//    FMT_I_OR_II       the table says "I, II" and the INSTRUCTION says which:
//                      Format I is `0 m d reg` and Format II is
//                      `1 m m' subop` in the same position, so bit 15 of the
//                      base word decides (p.3.293)
//    FMT_ESCAPE        the opcode is one of 0x58-0x5F, which carry a subop,
//                      and the format depends on it -- 0x5D is VIIb for EXTBF
//                      and CMPBF but VIIc for INSBF
//
//  op_format_first() gives the first two; op_format_escape() resolves the
//  third, from the same base-word byte that carries bit 15.
//============================================================================
`ifndef V60_OP_PKG_SV
`define V60_OP_PKG_SV

package v60_op_pkg;

import v60_fmt_pkg::*;

// The opcode byte alone.  Anything the table does not list is a reserved
// opcode -- "Reserved opcode exceptions occur when an attempt is made to
// execute an opcode which is not assigned a valid instruction"
// (Programmer's Reference S8).
function automatic insn_fmt_e op_format_first(input logic [7:0] op);
    insn_fmt_e r;
    begin
        case (op)
            8'h00: r = FMT_V;       // HALT
            8'h01: r = FMT_I_OR_II; // LDTASK
            8'h02: r = FMT_I_OR_II; // STPR
            8'h03: r = FMT_I_OR_II; // GETRA
            8'h04: r = FMT_I_OR_II; // GETPTE
            8'h05: r = FMT_I_OR_II; // GETATE
            8'h08: r = FMT_I_OR_II; // RVBIT
            8'h09: r = FMT_I_OR_II; // MOV.B
            8'h0A: r = FMT_I_OR_II; // MOVS.BH
            8'h0B: r = FMT_I_OR_II; // MOVZ.BH
            8'h0C: r = FMT_I_OR_II; // MOVS.BW
            8'h0D: r = FMT_I_OR_II; // MOVZ.BW
            8'h10: r = FMT_V;       // CLRTLBA
            8'h12: r = FMT_I_OR_II; // LDPR
            8'h13: r = FMT_I_OR_II; // UPDPSW.W
            8'h14: r = FMT_I_OR_II; // UPDPTE
            8'h15: r = FMT_I_OR_II; // UPDATE
            8'h19: r = FMT_I_OR_II; // MOVT.HB
            8'h1B: r = FMT_I_OR_II; // MOV.H
            8'h1C: r = FMT_I_OR_II; // MOVS.HW
            8'h1D: r = FMT_I_OR_II; // MOVZ.HW
            8'h20: r = FMT_I_OR_II; // IN
            8'h21: r = FMT_I_OR_II; // OUT
            8'h22: r = FMT_I_OR_II; // IN
            8'h23: r = FMT_I_OR_II; // OUT
            8'h24: r = FMT_I_OR_II; // IN
            8'h25: r = FMT_I_OR_II; // OUT
            8'h29: r = FMT_I_OR_II; // MOVT.WB
            8'h2B: r = FMT_I_OR_II; // MOVT.WH
            8'h2C: r = FMT_I_OR_II; // RVBYT
            8'h2D: r = FMT_I_OR_II; // MOV.W
            8'h38: r = FMT_I_OR_II; // NOT
            8'h39: r = FMT_I_OR_II; // NEG
            8'h3A: r = FMT_I_OR_II; // NOT
            8'h3B: r = FMT_I_OR_II; // NEG
            8'h3C: r = FMT_I_OR_II; // NOT
            8'h3D: r = FMT_I_OR_II; // NEG
            8'h3F: r = FMT_I_OR_II; // MOV.D
            8'h40: r = FMT_I_OR_II; // MOVEA
            8'h41: r = FMT_I_OR_II; // XCH
            8'h42: r = FMT_I_OR_II; // MOVEA
            8'h43: r = FMT_I_OR_II; // XCH
            8'h44: r = FMT_I_OR_II; // MOVEA
            8'h45: r = FMT_I_OR_II; // XCH
            8'h47: r = FMT_I_OR_II; // SETF
            8'h48: r = FMT_IV;      // BSR
            8'h49: r = FMT_II;      // CALL
            8'h4A: r = FMT_I_OR_II; // UPDPSW.H
            8'h4B: r = FMT_I_OR_II; // CHLVL
            8'h4C: r = FMT_I;       // CAXI
            8'h4D: r = FMT_I_OR_II; // CHKAR
            8'h4E: r = FMT_I_OR_II; // CHKAW
            8'h4F: r = FMT_I_OR_II; // CHKAE
            8'h50: r = FMT_I_OR_II; // REM
            8'h51: r = FMT_I_OR_II; // REMU
            8'h52: r = FMT_I_OR_II; // REM
            8'h53: r = FMT_I_OR_II; // REMU
            8'h54: r = FMT_I_OR_II; // REM
            8'h55: r = FMT_I_OR_II; // REMU
            8'h58: r = FMT_ESCAPE;  // escape
            8'h59: r = FMT_ESCAPE;  // escape
            8'h5A: r = FMT_ESCAPE;  // escape
            8'h5B: r = FMT_ESCAPE;  // escape
            8'h5C: r = FMT_ESCAPE;  // escape
            8'h5D: r = FMT_ESCAPE;  // escape
            8'h5E: r = FMT_ESCAPE;  // escape
            8'h5F: r = FMT_ESCAPE;  // escape
            8'h60: r = FMT_IV;      // Bcc
            8'h61: r = FMT_IV;      // Bcc
            8'h62: r = FMT_IV;      // Bcc
            8'h63: r = FMT_IV;      // Bcc
            8'h64: r = FMT_IV;      // Bcc
            8'h65: r = FMT_IV;      // Bcc
            8'h66: r = FMT_IV;      // Bcc
            8'h67: r = FMT_IV;      // Bcc
            8'h68: r = FMT_IV;      // Bcc
            8'h69: r = FMT_IV;      // Bcc
            8'h6A: r = FMT_IV;      // Bcc
            8'h6B: r = FMT_IV;      // Bcc
            8'h6C: r = FMT_IV;      // Bcc
            8'h6D: r = FMT_IV;      // Bcc
            8'h6E: r = FMT_IV;      // Bcc
            8'h6F: r = FMT_IV;      // Bcc
            8'h70: r = FMT_IV;      // Bcc
            8'h71: r = FMT_IV;      // Bcc
            8'h72: r = FMT_IV;      // Bcc
            8'h73: r = FMT_IV;      // Bcc
            8'h74: r = FMT_IV;      // Bcc
            8'h75: r = FMT_IV;      // Bcc
            8'h76: r = FMT_IV;      // Bcc
            8'h77: r = FMT_IV;      // Bcc
            8'h78: r = FMT_IV;      // Bcc
            8'h79: r = FMT_IV;      // Bcc
            8'h7A: r = FMT_IV;      // Bcc
            8'h7B: r = FMT_IV;      // Bcc
            8'h7C: r = FMT_IV;      // Bcc
            8'h7D: r = FMT_IV;      // Bcc
            8'h7E: r = FMT_IV;      // Bcc
            8'h7F: r = FMT_IV;      // Bcc
            8'h80: r = FMT_I_OR_II; // ADD
            8'h81: r = FMT_I_OR_II; // MUL
            8'h82: r = FMT_I_OR_II; // ADD
            8'h83: r = FMT_I_OR_II; // MUL
            8'h84: r = FMT_I_OR_II; // ADD
            8'h85: r = FMT_I_OR_II; // MUL
            8'h86: r = FMT_I_OR_II; // MULX
            8'h87: r = FMT_I_OR_II; // TEST1
            8'h88: r = FMT_I_OR_II; // OR
            8'h89: r = FMT_I_OR_II; // ROT
            8'h8A: r = FMT_I_OR_II; // OR
            8'h8B: r = FMT_I_OR_II; // ROT
            8'h8C: r = FMT_I_OR_II; // OR
            8'h8D: r = FMT_I_OR_II; // ROT
            8'h90: r = FMT_I_OR_II; // ADDC
            8'h91: r = FMT_I_OR_II; // MULU
            8'h92: r = FMT_I_OR_II; // ADDC
            8'h93: r = FMT_I_OR_II; // MULU
            8'h94: r = FMT_I_OR_II; // ADDC
            8'h95: r = FMT_I_OR_II; // MULU
            8'h96: r = FMT_I_OR_II; // MULUX
            8'h97: r = FMT_I_OR_II; // SET1
            8'h98: r = FMT_I_OR_II; // SUBC
            8'h99: r = FMT_I_OR_II; // ROTC
            8'h9A: r = FMT_I_OR_II; // SUBC
            8'h9B: r = FMT_I_OR_II; // ROTC
            8'h9C: r = FMT_I_OR_II; // SUBC
            8'h9D: r = FMT_I_OR_II; // ROTC
            8'hA0: r = FMT_I_OR_II; // AND
            8'hA1: r = FMT_I_OR_II; // DIV
            8'hA2: r = FMT_I_OR_II; // AND
            8'hA3: r = FMT_I_OR_II; // DIV
            8'hA4: r = FMT_I_OR_II; // AND
            8'hA5: r = FMT_I_OR_II; // DIV
            8'hA6: r = FMT_I_OR_II; // DIVX
            8'hA7: r = FMT_I_OR_II; // CLR1
            8'hA8: r = FMT_I_OR_II; // SUB
            8'hA9: r = FMT_I_OR_II; // SHL
            8'hAA: r = FMT_I_OR_II; // SUB
            8'hAB: r = FMT_I_OR_II; // SHL
            8'hAC: r = FMT_I_OR_II; // SUB
            8'hAD: r = FMT_I_OR_II; // SHL
            8'hB0: r = FMT_I_OR_II; // XOR
            8'hB1: r = FMT_I_OR_II; // DIVU
            8'hB2: r = FMT_I_OR_II; // XOR
            8'hB3: r = FMT_I_OR_II; // DIVU
            8'hB4: r = FMT_I_OR_II; // XOR
            8'hB5: r = FMT_I_OR_II; // DIVU
            8'hB6: r = FMT_I_OR_II; // DIVUX
            8'hB7: r = FMT_I_OR_II; // NOT1
            8'hB8: r = FMT_I_OR_II; // CMP
            8'hB9: r = FMT_I_OR_II; // SHA
            8'hBA: r = FMT_I_OR_II; // CMP
            8'hBB: r = FMT_I_OR_II; // SHA
            8'hBC: r = FMT_I_OR_II; // CMP
            8'hBD: r = FMT_I_OR_II; // SHA
            8'hC6: r = FMT_VI;      // DBcc
            8'hC7: r = FMT_VI;      // TB
            8'hC8: r = FMT_V;       // BRK
            8'hC9: r = FMT_V;       // BRKV
            8'hCA: r = FMT_V;       // RSR
            8'hCB: r = FMT_V;       // TRAPFL
            8'hCC: r = FMT_V;       // DISPOSE
            8'hCD: r = FMT_V;       // NOP
            8'hD0: r = FMT_III;     // DEC
            8'hD1: r = FMT_III;     // DEC
            8'hD2: r = FMT_III;     // DEC
            8'hD3: r = FMT_III;     // DEC
            8'hD4: r = FMT_III;     // DEC
            8'hD5: r = FMT_III;     // DEC
            8'hD6: r = FMT_III;     // JMP
            8'hD7: r = FMT_III;     // JMP
            8'hD8: r = FMT_III;     // INC
            8'hD9: r = FMT_III;     // INC
            8'hDA: r = FMT_III;     // INC
            8'hDB: r = FMT_III;     // INC
            8'hDC: r = FMT_III;     // INC
            8'hDD: r = FMT_III;     // INC
            8'hDE: r = FMT_II;      // PREPARE
            8'hDF: r = FMT_II;      // PREPARE
            8'hE0: r = FMT_III;     // TASI
            8'hE1: r = FMT_III;     // TASI
            8'hE2: r = FMT_III;     // RET
            8'hE3: r = FMT_III;     // RET
            8'hE4: r = FMT_II;      // POPM
            8'hE5: r = FMT_II;      // POPM
            8'hE6: r = FMT_II;      // POP
            8'hE7: r = FMT_II;      // POP
            8'hE8: r = FMT_III;     // JSR
            8'hE9: r = FMT_III;     // JSR
            8'hEA: r = FMT_III;     // RETIU
            8'hEB: r = FMT_III;     // RETIU
            8'hEC: r = FMT_II;      // PUSHM
            8'hED: r = FMT_II;      // PUSHM
            8'hEE: r = FMT_II;      // PUSH
            8'hEF: r = FMT_II;      // PUSH
            8'hF0: r = FMT_III;     // TEST
            8'hF1: r = FMT_III;     // TEST
            8'hF2: r = FMT_III;     // TEST
            8'hF3: r = FMT_III;     // TEST
            8'hF4: r = FMT_III;     // TEST
            8'hF5: r = FMT_III;     // TEST
            8'hF6: r = FMT_III;     // GETPSW
            8'hF7: r = FMT_III;     // GETPSW
            8'hF8: r = FMT_III;     // TRAP
            8'hF9: r = FMT_III;     // TRAP
            8'hFA: r = FMT_III;     // RETIS
            8'hFB: r = FMT_III;     // RETIS
            8'hFC: r = FMT_III;     // STTASK
            8'hFD: r = FMT_III;     // STTASK
            8'hFE: r = FMT_III;     // CLRTLB
            8'hFF: r = FMT_III;     // CLRTLB
            default: r = FMT_UNKNOWN;
        endcase
        op_format_first = r;
    end
endfunction

// The escape opcodes, resolved by the subop in the base word (bits 12:8).
function automatic insn_fmt_e op_format_escape(input logic [7:0] op,
                                               input logic [4:0] subop);
    insn_fmt_e r;
    begin
        case ({op, 3'b000, subop})
            16'h5800: r = FMT_VIIA;    // CMPC
            16'h5801: r = FMT_VIIA;    // CMPCF
            16'h5802: r = FMT_VIIA;    // CMPCS
            16'h5808: r = FMT_VIIA;    // MOVC
            16'h5809: r = FMT_VIIA;    // MOVC
            16'h580A: r = FMT_VIIA;    // MOVCF
            16'h580B: r = FMT_VIIA;    // MOVCF
            16'h580C: r = FMT_VIIA;    // MOVCS
            16'h5818: r = FMT_VIIB;    // SCHC
            16'h5819: r = FMT_VIIB;    // SCHC
            16'h581A: r = FMT_VIIB;    // SKPC
            16'h581B: r = FMT_VIIB;    // SKPC
            16'h5900: r = FMT_VIIC;    // ADDDC
            16'h5901: r = FMT_VIIC;    // SUBDC
            16'h5902: r = FMT_VIIC;    // SUBRDC
            16'h5910: r = FMT_VIIC;    // CVTD.PZ
            16'h5918: r = FMT_VIIC;    // CVTD.ZP
            16'h5A00: r = FMT_VIIA;    // CMPC
            16'h5A01: r = FMT_VIIA;    // CMPCF
            16'h5A02: r = FMT_VIIA;    // CMPCS
            16'h5A08: r = FMT_VIIA;    // MOVC
            16'h5A09: r = FMT_VIIA;    // MOVC
            16'h5A0A: r = FMT_VIIA;    // MOVCF
            16'h5A0B: r = FMT_VIIA;    // MOVCF
            16'h5A0C: r = FMT_VIIA;    // MOVCS
            16'h5A18: r = FMT_VIIB;    // SCHC
            16'h5A19: r = FMT_VIIB;    // SCHC
            16'h5A1A: r = FMT_VIIB;    // SKPC
            16'h5A1B: r = FMT_VIIB;    // SKPC
            16'h5B00: r = FMT_VIIB;    // SCH0BS
            16'h5B01: r = FMT_VIIB;    // SCH0BS
            16'h5B02: r = FMT_VIIB;    // SCH1BS
            16'h5B03: r = FMT_VIIB;    // SCH1BS
            16'h5B08: r = FMT_VIIB;    // MOVBS
            16'h5B09: r = FMT_VIIB;    // MOVBS
            16'h5B0A: r = FMT_VIIB;    // NOTBS
            16'h5B0B: r = FMT_VIIB;    // NOTBS
            16'h5B10: r = FMT_VIIB;    // ANDBS
            16'h5B11: r = FMT_VIIB;    // ANDBS
            16'h5B12: r = FMT_VIIB;    // ANDNBS
            16'h5B13: r = FMT_VIIB;    // ANDNBS
            16'h5B14: r = FMT_VIIB;    // ORBS
            16'h5B15: r = FMT_VIIB;    // ORBS
            16'h5B16: r = FMT_VIIB;    // ORNBS
            16'h5B17: r = FMT_VIIB;    // ORNBS
            16'h5B18: r = FMT_VIIB;    // XORBS
            16'h5B19: r = FMT_VIIB;    // XORBS
            16'h5B1A: r = FMT_VIIB;    // XORNBS
            16'h5B1B: r = FMT_VIIB;    // XORNBS
            16'h5C00: r = FMT_II;      // CMPF
            16'h5C08: r = FMT_II;      // MOVF
            16'h5C09: r = FMT_II;      // NEGF
            16'h5C0A: r = FMT_II;      // ABSF
            16'h5C10: r = FMT_II;      // SCLF
            16'h5C18: r = FMT_II;      // ADDF
            16'h5C19: r = FMT_II;      // SUBF
            16'h5C1A: r = FMT_II;      // MULF
            16'h5C1B: r = FMT_II;      // DIVF
            16'h5D00: r = FMT_VIIB;    // CMPBF
            16'h5D01: r = FMT_VIIB;    // CMPBF
            16'h5D02: r = FMT_VIIB;    // CMPBF
            16'h5D08: r = FMT_VIIB;    // EXTBF
            16'h5D09: r = FMT_VIIB;    // EXTBF
            16'h5D0A: r = FMT_VIIB;    // EXTBF
            16'h5D18: r = FMT_VIIC;    // INSBF
            16'h5D19: r = FMT_VIIC;    // INSBF
            16'h5D1A: r = FMT_VIIC;    // INSBF
            16'h5E00: r = FMT_II;      // CMPF
            16'h5E08: r = FMT_II;      // MOVF
            16'h5E09: r = FMT_II;      // NEGF
            16'h5E0A: r = FMT_II;      // ABSF
            16'h5E10: r = FMT_II;      // SCLF
            16'h5E18: r = FMT_II;      // ADDF
            16'h5E19: r = FMT_II;      // SUBF
            16'h5E1A: r = FMT_II;      // MULF
            16'h5E1B: r = FMT_II;      // DIVF
            16'h5F00: r = FMT_II;      // CVT.WS
            16'h5F01: r = FMT_II;      // CVT.SW
            16'h5F08: r = FMT_II;      // CVTF
            16'h5F09: r = FMT_II;      // CVT.LW
            16'h5F11: r = FMT_II;      // CVT.WL
            default: r = FMT_UNKNOWN;
        endcase
        op_format_escape = r;
    end
endfunction

// Format IV's displacement width, which is in the opcode and in two
// documents.  The databook prints Bcc as `011 b cccc` with the branch
// displacement table on p.3.295 giving "b = 0 byte / b = 1 halfword"; the
// Programmer's Reference S7 page for Bcc prints "Branch on Condition (byte
// displacement) 6x / (halfword displacement) 7x", and its BSR page prints the
// syntax as "bsr disp16".  Those are the only two Format IV opcodes.
function automatic logic [1:0] op_iv_disp_bytes(input logic [7:0] op);
    logic [1:0] r;
    begin
        case (op[7:4])
            4'h6:    r = 2'd1;   // Bcc, byte displacement
            4'h7:    r = 2'd2;   // Bcc, halfword displacement
            default: r = 2'd2;   // BSR: "bsr disp16"
        endcase
        op_iv_disp_bytes = r;
    end
endfunction

// The whole answer, given the opcode byte and the byte after it.  For a
// format with no second byte the second argument is ignored.
function automatic insn_fmt_e op_format(input logic [7:0] op,
                                        input logic [7:0] second);
    insn_fmt_e f;
    begin
        f = op_format_first(op);
        if (f == FMT_I_OR_II) begin
            if (second[7]) f = FMT_II;
            else           f = FMT_I;
        end else if (f == FMT_ESCAPE) begin
            f = op_format_escape(op, second[4:0]);
        end
        op_format = f;
    end
endfunction

endpackage

`endif
