#!/usr/bin/env python3
"""Generate rtl/cpu/v60x/v60_op_pkg.sv from tools/v60x/insn_table.py.

The table is data, so the RTL is generated from it rather than hand-written
beside it -- a hand-written copy is a second statement of the same fact, and
this project has already had to delete one of those.

`run_v60x.sh` regenerates into a temporary file and diffs, so a table edit
that was not regenerated fails the bench run.

Usage:  python3 tools/v60x/gen_op_pkg.py [outfile]
"""

import sys

from insn_table import TABLE, expand, check_table

HEADER = '''//============================================================================
//  v60_op_pkg -- which instruction format an opcode is.
//
//  GENERATED by tools/v60x/gen_op_pkg.py from tools/v60x/insn_table.py.
//  Do not edit: edit the table and regenerate.  verif/v60x/run_v60x.sh checks
//  that this file matches its source.
//
//  Source: NEC_uPD70616_V60_DataBook_1986.pdf pp.3.296-3.299, the instruction
//  set summary's "Instruction Format" column, cross-checked where it can be
//  against the Programmer's Reference.  docs/v60/INSTRUCTION-FORMATS.md
//  carries the traps; tools/v60x/insn_table.py carries the table, the
//  placeholder-field expansion, the collision check and the two places the two
//  NEC documents disagree.
//
//  Three answers are possible for one opcode byte:
//
//    a format          the opcode says, on its own
//    FMT_I_OR_II       the table says "I, II" and the INSTRUCTION says which:
//                      Format I is `0 m d reg` and Format II is
//                      `1 m m' subop` in the same position, so bit 15 of the
//                      base word decides (p.3.293)
//    FMT_ESCAPE        the opcode is one of 0x58-0x5F, which carry a subop,
//                      and the format depends on it -- 0x5D is VIIb for EXTBF
//                      and CMPBF but VIIc for INSBF
//
//  op_format_first() gives the first two; op_format_escape() resolves the
//  third, from the same base-word byte that carries bit 15.
//============================================================================
`ifndef V60_OP_PKG_SV
`define V60_OP_PKG_SV

package v60_op_pkg;

import v60_fmt_pkg::*;
'''

FOOTER = '''
endpackage

`endif
'''

SV_FMT = {
    'I': 'FMT_I', 'II': 'FMT_II', 'III': 'FMT_III', 'IV': 'FMT_IV',
    'V': 'FMT_V', 'VI': 'FMT_VI', 'VIIa': 'FMT_VIIA', 'VIIb': 'FMT_VIIB',
    'VIIc': 'FMT_VIIC', 'I,II': 'FMT_I_OR_II',
}


def build():
    """(first[256], escape{(op, subop): fmt}, mnemonic_of{})"""
    first = {}
    escape = {}
    who = {}

    for mnemonic, op, subop, fmt, page in TABLE:
        for b in expand(op):
            if subop is None:
                first[b] = SV_FMT[fmt]
                who[b] = mnemonic
            else:
                first[b] = 'FMT_ESCAPE'
                who[b] = 'escape'
                for s in expand(subop):
                    assert s < 32, ('%s: subop %02X does not fit the five bits '
                                    'the base word gives it' % (mnemonic, s))
                    escape[(b, s)] = (SV_FMT[fmt], mnemonic)
    return first, escape, who


def emit(out):
    errors, collisions = check_table()
    if errors or collisions:
        raise SystemExit('table does not validate; run insn_table.py')

    first, escape, who = build()
    w = out.write
    w(HEADER)

    w('''
// The opcode byte alone.  Anything the table does not list is a reserved
// opcode -- "Reserved opcode exceptions occur when an attempt is made to
// execute an opcode which is not assigned a valid instruction"
// (Programmer's Reference S8).
function automatic insn_fmt_e op_format_first(input logic [7:0] op);
    insn_fmt_e r;
    begin
        case (op)
''')
    for b in range(256):
        if b in first:
            w('            8\'h%02X: r = %-12s // %s\n'
              % (b, first[b] + ';', who[b]))
    w('''            default: r = FMT_UNKNOWN;
        endcase
        op_format_first = r;
    end
endfunction

// The escape opcodes, resolved by the subop in the base word (bits 12:8).
function automatic insn_fmt_e op_format_escape(input logic [7:0] op,
                                               input logic [4:0] subop);
    insn_fmt_e r;
    begin
        case ({op, 3'b000, subop})
''')
    for (b, s), (fmt, mnemonic) in sorted(escape.items()):
        w('            16\'h%02X%02X: r = %-12s // %s\n' % (b, s, fmt + ';', mnemonic))
    w('''            default: r = FMT_UNKNOWN;
        endcase
        op_format_escape = r;
    end
endfunction

// Format IV's displacement width, which is in the opcode and in two
// documents.  The databook prints Bcc as `011 b cccc` with the branch
// displacement table on p.3.295 giving "b = 0 byte / b = 1 halfword"; the
// Programmer's Reference S7 page for Bcc prints "Branch on Condition (byte
// displacement) 6x / (halfword displacement) 7x", and its BSR page prints the
// syntax as "bsr disp16".  Those are the only two Format IV opcodes.
function automatic logic [1:0] op_iv_disp_bytes(input logic [7:0] op);
    logic [1:0] r;
    begin
        case (op[7:4])
            4'h6:    r = 2'd1;   // Bcc, byte displacement
            4'h7:    r = 2'd2;   // Bcc, halfword displacement
            default: r = 2'd2;   // BSR: "bsr disp16"
        endcase
        op_iv_disp_bytes = r;
    end
endfunction

// The whole answer, given the opcode byte and the byte after it.  For a
// format with no second byte the second argument is ignored.
function automatic insn_fmt_e op_format(input logic [7:0] op,
                                        input logic [7:0] second);
    insn_fmt_e f;
    begin
        f = op_format_first(op);
        if (f == FMT_I_OR_II) begin
            if (second[7]) f = FMT_II;
            else           f = FMT_I;
        end else if (f == FMT_ESCAPE) begin
            f = op_format_escape(op, second[4:0]);
        end
        op_format = f;
    end
endfunction
''')
    w(FOOTER)


def main():
    path = sys.argv[1] if len(sys.argv) > 1 else 'rtl/cpu/v60x/v60_op_pkg.sv'
    with open(path, 'w') as out:
        emit(out)
    first, escape, _ = build()
    print('%s: %d opcode bytes, %d escape encodings'
          % (path, len(first), len(escape)))


if __name__ == '__main__':
    main()
