#!/usr/bin/env python3
"""Generate rtl/cpu/v60x/v60_op_pkg.sv from tools/v60x/insn_table.py.

The table is data, so the RTL is generated from it rather than hand-written
beside it -- a hand-written copy is a second statement of the same fact, and
this project has already had to delete one of those.

`run_v60x.sh` regenerates into a temporary file and diffs, so a table edit
that was not regenerated fails the bench run.

Usage:  python3 tools/v60x/gen_op_pkg.py [outfile]
"""

import sys

from insn_table import (TABLE, DATA_TYPE, EXEC_OP, EXEC_OP_ESCAPE, CTRL_OP,
                        expand, check_table)

HEADER = '''//============================================================================
//  v60_op_pkg -- which instruction format an opcode is.
//
//  GENERATED by tools/v60x/gen_op_pkg.py from tools/v60x/insn_table.py.
//  Do not edit: edit the table and regenerate.  verif/v60x/run_v60x.sh checks
//  that this file matches its source.
//
//  Source: NEC_uPD70616_V60_DataBook_1986.pdf pp.3.296-3.299, the instruction
//  set summary's "Instruction Format" column, cross-checked where it can be
//  against the Programmer's Reference.  docs/v60/INSTRUCTION-FORMATS.md
//  carries the traps; tools/v60x/insn_table.py carries the table, the
//  placeholder-field expansion, the collision check and the two places the two
//  NEC documents disagree.
//
//  Three answers are possible for one opcode byte:
//
//    a format          the opcode says, on its own
//    FMT_I_OR_II       the table says "I, II" and the INSTRUCTION says which:
//                      Format I is `0 m d reg` and Format II is
//                      `1 m m' subop` in the same position, so bit 15 of the
//                      base word decides (p.3.293)
//    FMT_ESCAPE        the opcode is one of 0x58-0x5F, which carry a subop,
//                      and the format depends on it -- 0x5D is VIIb for EXTBF
//                      and CMPBF but VIIc for INSBF
//
//  op_format_first() gives the first two; op_format_escape() resolves the
//  third, from the same base-word byte that carries bit 15.
//============================================================================
`ifndef V60_OP_PKG_SV
`define V60_OP_PKG_SV

package v60_op_pkg;

import v60_fmt_pkg::*;
import v60_alu_pkg::*;

// The control transfers, which do not go through the ALU.  Their operations
// are quoted in tools/v60x/insn_table.py beside the table that names them.
typedef enum logic [3:0] {
    CTRL_NONE = 4'd0,
    CTRL_BCC  = 4'd1,   // conditional, PC relative
    CTRL_BSR  = 4'd2,   // PC relative, pushes the return address
    CTRL_JMP  = 4'd3,   // to an effective address
    CTRL_JSR  = 4'd4,   // to an effective address, pushes the return address
    CTRL_RSR  = 4'd5,   // pops it
    CTRL_DBCC = 4'd6,   // decrement, and branch while not zero
    CTRL_TB   = 4'd7,   // branch when the register is zero
    CTRL_CALL = 4'd8,   // to an effective address, passing the argument pointer
    CTRL_RET  = 4'd9,   // pops the PC and the argument pointer, then discards
    CTRL_RETIU= 4'd10,  // pops the PC and the PSW
    CTRL_RETIS= 4'd11   // the same, and privileged
} ctrl_op_e;
'''

FOOTER = '''
endpackage

`endif
'''

SV_FMT = {
    'I': 'FMT_I', 'II': 'FMT_II', 'III': 'FMT_III', 'IV': 'FMT_IV',
    'V': 'FMT_V', 'VI': 'FMT_VI', 'VIIa': 'FMT_VIIA', 'VIIb': 'FMT_VIIB',
    'VIIc': 'FMT_VIIC', 'I,II': 'FMT_I_OR_II',
}


DATA_NONE    = 0      # the operand is not a datum of a width
DATA_UNKNOWN = 15     # this table does not carry it; see insn_table.py


def data_width(spec, byte):
    """One operand's unit size for one concrete opcode byte.

    `siz`, `s` and `c` are fields of the byte, and insn_table's check_table()
    has already proved each sits where this reads it, so the width resolves
    here rather than in RTL: the generated table is per byte value.
    """
    if spec is None:
        return DATA_NONE
    if spec == '?':
        return DATA_UNKNOWN
    if spec == 'siz':
        return {0: 1, 1: 2, 2: 4}.get((byte >> 1) & 3, DATA_UNKNOWN)
    if spec == 's':
        return 8 if (byte >> 1) & 1 else 4     # long real / short real
    if spec == 'c':
        return 2 if (byte >> 1) & 1 else 1     # halfword / byte character
    return spec


def build():
    """(first[256], escape{(op, subop): fmt}, mnemonic_of{})"""
    first = {}
    escape = {}
    who = {}
    width = {}        # opcode byte      -> (w1, w2)
    width_esc = {}    # (opcode, subop)  -> (w1, w2)
    escalu   = []     # ((opcode, subop), alu_op, mnemonic)
    execop = {}       # opcode byte      -> the ALU operation, or None
    ctrlop = {}       # opcode byte      -> the control transfer, or None

    def put(store, key, value, mnemonic, other):
        # Two instructions on one key must agree about the operand widths.
        # They do not always: the floating point opcodes 5C/5E carry MOVF and
        # SCLF alike, and SCLF's first operand is an integer scale factor
        # where MOVF's is a real.  That is what the subop is for.
        if key in store and store[key] != value:
            raise SystemExit(
                '%s and %s share %s but disagree about operand widths '
                '(%s vs %s) -- the width has to be keyed by subop'
                % (mnemonic, other.get(key, '?'), key, store[key], value))
        store[key] = value
        other[key] = mnemonic

    who_esc = {}
    for mnemonic, op, subop, fmt, page in TABLE:
        w1, w2 = DATA_TYPE[mnemonic]
        for b in expand(op):
            widths = (data_width(w1, b), data_width(w2, b))
            if subop is None:
                first[b] = SV_FMT[fmt]
                who[b] = mnemonic
                execop[b] = EXEC_OP.get(mnemonic)
                ctrlop[b] = CTRL_OP.get(mnemonic)
                put(width, b, widths, mnemonic, who)
            else:
                first[b] = 'FMT_ESCAPE'
                who[b] = 'escape'
                for s in expand(subop):
                    assert s < 32, ('%s: subop %02X does not fit the five bits '
                                    'the base word gives it' % (mnemonic, s))
                    escape[(b, s)] = (SV_FMT[fmt], mnemonic)
                    # And, where the sub-op picks the OPERATION rather than
                    # only the format, the ALU op for this exact (op, subop).
                    # `ext` is the sub-op's low two bits (p.3.295).
                    if (mnemonic, s & 3) in EXEC_OP_ESCAPE:
                        escalu.append(((b, s),
                                       EXEC_OP_ESCAPE[(mnemonic, s & 3)],
                                       mnemonic))
                    put(width_esc, (b, s), widths, mnemonic, who_esc)
    return (first, escape, who, width, width_esc, who_esc, execop, ctrlop,
            escalu)


def emit(out):
    errors, collisions = check_table()
    if errors or collisions:
        raise SystemExit('table does not validate; run insn_table.py')

    (first, escape, who, width, width_esc, who_esc, execop, ctrlop,
     escalu) = build()
    w = out.write
    w(HEADER)

    w('''
// The opcode byte alone.  Anything the table does not list is a reserved
// opcode -- "Reserved opcode exceptions occur when an attempt is made to
// execute an opcode which is not assigned a valid instruction"
// (Programmer's Reference S8).
function automatic insn_fmt_e op_format_first(input logic [7:0] op);
    insn_fmt_e r;
    begin
        case (op)
''')
    for b in range(256):
        if b in first:
            w('            8\'h%02X: r = %-12s // %s\n'
              % (b, first[b] + ';', who[b]))
    w('''            default: r = FMT_UNKNOWN;
        endcase
        op_format_first = r;
    end
endfunction

// The escape opcodes, resolved by the subop in the base word (bits 12:8).
function automatic insn_fmt_e op_format_escape(input logic [7:0] op,
                                               input logic [4:0] subop);
    insn_fmt_e r;
    begin
        case ({op, 3'b000, subop})
''')
    for (b, s), (fmt, mnemonic) in sorted(escape.items()):
        w('            16\'h%02X%02X: r = %-12s // %s\n' % (b, s, fmt + ';', mnemonic))
    w('''            default: r = FMT_UNKNOWN;
        endcase
        op_format_escape = r;
    end
endfunction

// The operand's data type, as its UNIT SIZE in bytes -- the constant p.3.261
// scales an index by and steps [Rn+] by, and the width an immed.N takes
// (p.3.294 gives one mode code three rows, so the mode field cannot say).
//
// It is NOT a variable-length operand's length: that is the extension field's
// (p.3.293), and it reaches the sequencer as v60_idu's opN_ext.
//
//   0   this operand is not a datum of a width -- a displacement, a register
//       number, or an instruction with no operands
//   15  the instruction has a data operand whose width the table does not
//       carry; see tools/v60x/insn_table.py.  Callers fall back and say so.
function automatic logic [3:0] op_data_bytes_first(input logic [7:0] op,
                                                   input logic       second);
    logic [3:0] r;
    begin
        case ({op, second})
''')
    for b in range(256):
        if b in width:
            for which in (0, 1):
                w('            9\'h%03X: r = 4\'d%-2d;  // %s%s\n'
                  % ((b << 1) | which, width[b][which], who[b],
                     '' if which == 0 else " (operand 2)"))
    w('''            default: r = 4'd15;    // not an instruction: nothing to say
        endcase
        op_data_bytes_first = r;
    end
endfunction

// The escape opcodes again: 5C and 5E carry MOVF and SCLF alike, and their
// first operands are not the same kind of thing, so the width is keyed by the
// subop exactly as the format is.
function automatic logic [3:0] op_data_bytes_escape(input logic [7:0] op,
                                                    input logic [4:0] subop,
                                                    input logic       second);
    logic [3:0] r;
    begin
        case ({op, 2'b00, subop, second})
''')
    for (b, sub) in sorted(width_esc):
        for which in (0, 1):
            w('            16\'h%04X: r = 4\'d%-2d;  // %s%s\n'
              % ((b << 8) | (sub << 1) | which, width_esc[(b, sub)][which],
                 who_esc[(b, sub)], '' if which == 0 else " (operand 2)"))
    w('''            default: r = 4'd15;
        endcase
        op_data_bytes_escape = r;
    end
endfunction

// The whole answer.  `subop` is the base word's, and is ignored unless the
// opcode is one of the escapes.
function automatic logic [3:0] op_data_bytes(input logic [7:0] op,
                                             input logic [4:0] subop,
                                             input logic       second);
    logic [3:0] r;
    begin
        if (op_format_first(op) == FMT_ESCAPE)
            r = op_data_bytes_escape(op, subop, second);
        else
            r = op_data_bytes_first(op, second);
        op_data_bytes = r;
    end
endfunction

// What the instruction does, for the ones v60_alu implements.  ALU_NONE means
// the sequencer can decode and address it but not execute it.
function automatic alu_op_e op_alu(input logic [7:0] op);
    alu_op_e r;
    begin
        case (op)
''')
    for b in range(256):
        if execop.get(b):
            w('            8\'h%02X: r = ALU_%-5s // %s\n'
              % (b, execop[b] + ';', who[b]))
    w('''            default: r = ALU_NONE;
        endcase
        op_alu = r;
    end
endfunction

// The escape opcodes whose SUB-OP picks the OPERATION, not just the width.
// 0x5D is EXTBF, INSBF and CMPBF together, and p.3.295's two-bit `ext` field in
// the sub-op byte selects the variant of each -- so one opcode byte carries
// eight operations and op_alu(), keyed by opcode alone, cannot express it.
function automatic alu_op_e op_alu_escape(input logic [7:0] op,
                                          input logic [4:0] subop);
    alu_op_e r;
    begin
        case ({op, 3'b000, subop})
''')
    for (b, sb), aluop, mn in sorted(escalu):
        w('            16\'h%02X%02X: r = ALU_%-8s // %s\n'
          % (b, sb, aluop + ';', mn))
    w('''            default: r = ALU_NONE;
        endcase
        op_alu_escape = r;
    end
endfunction

// The whole answer.  The escape's operation if it has one, and the opcode's
// otherwise -- the same shape as op_data_bytes() below, for the same reason.
function automatic alu_op_e op_alu_all(input logic [7:0] op,
                                       input logic [4:0] subop);
    alu_op_e e;
    begin
        // if/else and not a ternary: a ternary between two enum values is not
        // an enum to every tool, which this file's own dst_mode note records.
        e = op_alu_escape(op, subop);
        if (e != ALU_NONE) op_alu_all = e;
        else               op_alu_all = op_alu(op);
    end
endfunction

// Which control transfer an opcode is, if any.
function automatic ctrl_op_e op_ctrl(input logic [7:0] op);
    ctrl_op_e r;
    begin
        case (op)
''')
    for b in range(256):
        if ctrlop.get(b):
            w('            8\'h%02X: r = CTRL_%-5s // %s\n'
              % (b, ctrlop[b] + ';', who[b]))
    w('''            default: r = CTRL_NONE;
        endcase
        op_ctrl = r;
    end
endfunction

// Format IV's displacement width, which is in the opcode and in two
// documents.  The databook prints Bcc as `011 b cccc` with the branch
// displacement table on p.3.295 giving "b = 0 byte / b = 1 halfword"; the
// Programmer's Reference S7 page for Bcc prints "Branch on Condition (byte
// displacement) 6x / (halfword displacement) 7x", and its BSR page prints the
// syntax as "bsr disp16".  Those are the only two Format IV opcodes.
function automatic logic [1:0] op_iv_disp_bytes(input logic [7:0] op);
    logic [1:0] r;
    begin
        case (op[7:4])
            4'h6:    r = 2'd1;   // Bcc, byte displacement
            4'h7:    r = 2'd2;   // Bcc, halfword displacement
            default: r = 2'd2;   // BSR: "bsr disp16"
        endcase
        op_iv_disp_bytes = r;
    end
endfunction

// The whole answer, given the opcode byte and the byte after it.  For a
// format with no second byte the second argument is ignored.
function automatic insn_fmt_e op_format(input logic [7:0] op,
                                        input logic [7:0] second);
    insn_fmt_e f;
    begin
        f = op_format_first(op);
        if (f == FMT_I_OR_II) begin
            if (second[7]) f = FMT_II;
            else           f = FMT_I;
        end else if (f == FMT_ESCAPE) begin
            f = op_format_escape(op, second[4:0]);
        end
        op_format = f;
    end
endfunction
''')
    w(FOOTER)


def main():
    path = sys.argv[1] if len(sys.argv) > 1 else 'rtl/cpu/v60x/v60_op_pkg.sv'
    with open(path, 'w') as out:
        emit(out)
    (first, escape, _, width, width_esc, _w, execop, ctrlop, _e) = build()
    print('%s: %d opcode bytes, %d escape encodings, %d widths (%d by subop), '
          '%d executable, %d control'
          % (path, len(first), len(escape), len(width), len(width_esc),
             len([v for v in execop.values() if v]),
             len([v for v in ctrlop.values() if v])))


if __name__ == '__main__':
    main()
